/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CashBoxesReadIdParameter,
  CompositeAmountReadAllResponse,
  HttpValidationProblemDetails,
} from '../models/index';
import {
    CashBoxesReadIdParameterFromJSON,
    CashBoxesReadIdParameterToJSON,
    CompositeAmountReadAllResponseFromJSON,
    CompositeAmountReadAllResponseToJSON,
    HttpValidationProblemDetailsFromJSON,
    HttpValidationProblemDetailsToJSON,
} from '../models/index';

export interface CompositeAmountsGetRequest {
    storeId: CashBoxesReadIdParameter;
    page?: CashBoxesReadIdParameter;
    pageSize?: CashBoxesReadIdParameter;
}

/**
 * 
 */
export class CompositeAmountsApi extends runtime.BaseAPI {

    /**
     */
    async compositeAmountsGetRaw(requestParameters: CompositeAmountsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CompositeAmountReadAllResponse>> {
        if (requestParameters['storeId'] == null) {
            throw new runtime.RequiredError(
                'storeId',
                'Required parameter "storeId" was null or undefined when calling compositeAmountsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['storeId'] != null) {
            queryParameters['StoreId'] = requestParameters['storeId'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['Page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/composite-amounts`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CompositeAmountReadAllResponseFromJSON(jsonValue));
    }

    /**
     */
    async compositeAmountsGet(requestParameters: CompositeAmountsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CompositeAmountReadAllResponse> {
        const response = await this.compositeAmountsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
