/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ContainerTemplateCreateRequest,
  ContainerTemplateCreateResponse,
  ContainerTemplateReadAllResponse,
  ContainerTemplateUpdateRequestModel,
  ContainerTemplateUpdateResponse,
  HttpValidationProblemDetails,
} from '../models/index';
import {
    ContainerTemplateCreateRequestFromJSON,
    ContainerTemplateCreateRequestToJSON,
    ContainerTemplateCreateResponseFromJSON,
    ContainerTemplateCreateResponseToJSON,
    ContainerTemplateReadAllResponseFromJSON,
    ContainerTemplateReadAllResponseToJSON,
    ContainerTemplateUpdateRequestModelFromJSON,
    ContainerTemplateUpdateRequestModelToJSON,
    ContainerTemplateUpdateResponseFromJSON,
    ContainerTemplateUpdateResponseToJSON,
    HttpValidationProblemDetailsFromJSON,
    HttpValidationProblemDetailsToJSON,
} from '../models/index';

export interface ContainerTemplatesCreateRequest {
    containerTemplateCreateRequest: ContainerTemplateCreateRequest;
}

export interface ContainerTemplatesDeleteRequest {
    id: number;
}

export interface ContainerTemplatesReadAllRequest {
    name?: string;
    storeItemId?: number;
    page?: number;
    pageSize?: number;
}

export interface ContainerTemplatesUpdateRequest {
    id: number;
    containerTemplateUpdateRequestModel: ContainerTemplateUpdateRequestModel;
}

/**
 * 
 */
export class ContainerTemplatesApi extends runtime.BaseAPI {

    /**
     */
    async containerTemplatesCreateRaw(requestParameters: ContainerTemplatesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContainerTemplateCreateResponse>> {
        if (requestParameters['containerTemplateCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'containerTemplateCreateRequest',
                'Required parameter "containerTemplateCreateRequest" was null or undefined when calling containerTemplatesCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/container-templates`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ContainerTemplateCreateRequestToJSON(requestParameters['containerTemplateCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContainerTemplateCreateResponseFromJSON(jsonValue));
    }

    /**
     */
    async containerTemplatesCreate(requestParameters: ContainerTemplatesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContainerTemplateCreateResponse> {
        const response = await this.containerTemplatesCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async containerTemplatesDeleteRaw(requestParameters: ContainerTemplatesDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling containerTemplatesDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/container-templates/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async containerTemplatesDelete(requestParameters: ContainerTemplatesDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.containerTemplatesDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async containerTemplatesReadAllRaw(requestParameters: ContainerTemplatesReadAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContainerTemplateReadAllResponse>> {
        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['Name'] = requestParameters['name'];
        }

        if (requestParameters['storeItemId'] != null) {
            queryParameters['StoreItemId'] = requestParameters['storeItemId'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['Page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/container-templates`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContainerTemplateReadAllResponseFromJSON(jsonValue));
    }

    /**
     */
    async containerTemplatesReadAll(requestParameters: ContainerTemplatesReadAllRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContainerTemplateReadAllResponse> {
        const response = await this.containerTemplatesReadAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async containerTemplatesUpdateRaw(requestParameters: ContainerTemplatesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContainerTemplateUpdateResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling containerTemplatesUpdate().'
            );
        }

        if (requestParameters['containerTemplateUpdateRequestModel'] == null) {
            throw new runtime.RequiredError(
                'containerTemplateUpdateRequestModel',
                'Required parameter "containerTemplateUpdateRequestModel" was null or undefined when calling containerTemplatesUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/container-templates/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ContainerTemplateUpdateRequestModelToJSON(requestParameters['containerTemplateUpdateRequestModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContainerTemplateUpdateResponseFromJSON(jsonValue));
    }

    /**
     */
    async containerTemplatesUpdate(requestParameters: ContainerTemplatesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContainerTemplateUpdateResponse> {
        const response = await this.containerTemplatesUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
