/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CashBoxesReadIdParameter,
  HttpValidationProblemDetails,
  LayoutCreateRequestModel,
  LayoutCreateResponse,
  LayoutReadAllResponse,
  LayoutReadResponse,
  LayoutUpdateRequestModel,
  LayoutUpdateResponse,
} from '../models/index';
import {
    CashBoxesReadIdParameterFromJSON,
    CashBoxesReadIdParameterToJSON,
    HttpValidationProblemDetailsFromJSON,
    HttpValidationProblemDetailsToJSON,
    LayoutCreateRequestModelFromJSON,
    LayoutCreateRequestModelToJSON,
    LayoutCreateResponseFromJSON,
    LayoutCreateResponseToJSON,
    LayoutReadAllResponseFromJSON,
    LayoutReadAllResponseToJSON,
    LayoutReadResponseFromJSON,
    LayoutReadResponseToJSON,
    LayoutUpdateRequestModelFromJSON,
    LayoutUpdateRequestModelToJSON,
    LayoutUpdateResponseFromJSON,
    LayoutUpdateResponseToJSON,
} from '../models/index';

export interface LayoutsGetRequest {
    name?: string;
}

export interface LayoutsIdDeleteRequest {
    id: number;
}

export interface LayoutsIdPutRequest {
    id: CashBoxesReadIdParameter;
    layoutUpdateRequestModel: LayoutUpdateRequestModel;
    storeId?: CashBoxesReadIdParameter;
}

export interface LayoutsPostRequest {
    layoutCreateRequestModel: LayoutCreateRequestModel;
    storeId?: CashBoxesReadIdParameter;
}

export interface LayoutsReadRequest {
    id: CashBoxesReadIdParameter;
    storeId?: CashBoxesReadIdParameter;
}

export interface LayoutsTopLevelGetRequest {
    storeId?: CashBoxesReadIdParameter;
}

/**
 * 
 */
export class LayoutsApi extends runtime.BaseAPI {

    /**
     */
    async layoutsGetRaw(requestParameters: LayoutsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LayoutReadAllResponse>> {
        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['Name'] = requestParameters['name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/layouts`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LayoutReadAllResponseFromJSON(jsonValue));
    }

    /**
     */
    async layoutsGet(requestParameters: LayoutsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LayoutReadAllResponse> {
        const response = await this.layoutsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async layoutsIdDeleteRaw(requestParameters: LayoutsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling layoutsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/layouts/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async layoutsIdDelete(requestParameters: LayoutsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.layoutsIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async layoutsIdPutRaw(requestParameters: LayoutsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LayoutUpdateResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling layoutsIdPut().'
            );
        }

        if (requestParameters['layoutUpdateRequestModel'] == null) {
            throw new runtime.RequiredError(
                'layoutUpdateRequestModel',
                'Required parameter "layoutUpdateRequestModel" was null or undefined when calling layoutsIdPut().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['storeId'] != null) {
            queryParameters['StoreId'] = requestParameters['storeId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/layouts/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: LayoutUpdateRequestModelToJSON(requestParameters['layoutUpdateRequestModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LayoutUpdateResponseFromJSON(jsonValue));
    }

    /**
     */
    async layoutsIdPut(requestParameters: LayoutsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LayoutUpdateResponse> {
        const response = await this.layoutsIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async layoutsPostRaw(requestParameters: LayoutsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LayoutCreateResponse>> {
        if (requestParameters['layoutCreateRequestModel'] == null) {
            throw new runtime.RequiredError(
                'layoutCreateRequestModel',
                'Required parameter "layoutCreateRequestModel" was null or undefined when calling layoutsPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['storeId'] != null) {
            queryParameters['StoreId'] = requestParameters['storeId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/layouts`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LayoutCreateRequestModelToJSON(requestParameters['layoutCreateRequestModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LayoutCreateResponseFromJSON(jsonValue));
    }

    /**
     */
    async layoutsPost(requestParameters: LayoutsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LayoutCreateResponse> {
        const response = await this.layoutsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async layoutsReadRaw(requestParameters: LayoutsReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LayoutReadResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling layoutsRead().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['storeId'] != null) {
            queryParameters['StoreId'] = requestParameters['storeId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/layouts/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LayoutReadResponseFromJSON(jsonValue));
    }

    /**
     */
    async layoutsRead(requestParameters: LayoutsReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LayoutReadResponse> {
        const response = await this.layoutsReadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async layoutsTopLevelGetRaw(requestParameters: LayoutsTopLevelGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LayoutReadResponse>> {
        const queryParameters: any = {};

        if (requestParameters['storeId'] != null) {
            queryParameters['StoreId'] = requestParameters['storeId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/layouts/top-level`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LayoutReadResponseFromJSON(jsonValue));
    }

    /**
     */
    async layoutsTopLevelGet(requestParameters: LayoutsTopLevelGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LayoutReadResponse> {
        const response = await this.layoutsTopLevelGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
