/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HttpValidationProblemDetails,
  ModifierCreateRequest,
  ModifierCreateResponse,
  ModifierReadAllResponse,
  ModifierReadResponse,
  ModifierUpdateModel,
  ModifierUpdateResponse,
} from '../models/index';
import {
    HttpValidationProblemDetailsFromJSON,
    HttpValidationProblemDetailsToJSON,
    ModifierCreateRequestFromJSON,
    ModifierCreateRequestToJSON,
    ModifierCreateResponseFromJSON,
    ModifierCreateResponseToJSON,
    ModifierReadAllResponseFromJSON,
    ModifierReadAllResponseToJSON,
    ModifierReadResponseFromJSON,
    ModifierReadResponseToJSON,
    ModifierUpdateModelFromJSON,
    ModifierUpdateModelToJSON,
    ModifierUpdateResponseFromJSON,
    ModifierUpdateResponseToJSON,
} from '../models/index';

export interface ModifiersCreateRequest {
    modifierCreateRequest: ModifierCreateRequest;
}

export interface ModifiersDeleteRequest {
    id: number;
}

export interface ModifiersReadRequest {
    id: number;
}

export interface ModifiersReadAllRequest {
    name?: string;
    categoryId?: number;
    targetId?: number;
    page?: number;
    pageSize?: number;
}

export interface ModifiersUpdateRequest {
    id: number;
    modifierUpdateModel: ModifierUpdateModel;
}

/**
 * 
 */
export class ModifiersApi extends runtime.BaseAPI {

    /**
     */
    async modifiersCreateRaw(requestParameters: ModifiersCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModifierCreateResponse>> {
        if (requestParameters['modifierCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'modifierCreateRequest',
                'Required parameter "modifierCreateRequest" was null or undefined when calling modifiersCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/modifiers`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ModifierCreateRequestToJSON(requestParameters['modifierCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModifierCreateResponseFromJSON(jsonValue));
    }

    /**
     */
    async modifiersCreate(requestParameters: ModifiersCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModifierCreateResponse> {
        const response = await this.modifiersCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async modifiersDeleteRaw(requestParameters: ModifiersDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling modifiersDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/modifiers/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async modifiersDelete(requestParameters: ModifiersDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.modifiersDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async modifiersReadRaw(requestParameters: ModifiersReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModifierReadResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling modifiersRead().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/modifers/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModifierReadResponseFromJSON(jsonValue));
    }

    /**
     */
    async modifiersRead(requestParameters: ModifiersReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModifierReadResponse> {
        const response = await this.modifiersReadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async modifiersReadAllRaw(requestParameters: ModifiersReadAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModifierReadAllResponse>> {
        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['Name'] = requestParameters['name'];
        }

        if (requestParameters['categoryId'] != null) {
            queryParameters['CategoryId'] = requestParameters['categoryId'];
        }

        if (requestParameters['targetId'] != null) {
            queryParameters['TargetId'] = requestParameters['targetId'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['Page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/modifiers`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModifierReadAllResponseFromJSON(jsonValue));
    }

    /**
     */
    async modifiersReadAll(requestParameters: ModifiersReadAllRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModifierReadAllResponse> {
        const response = await this.modifiersReadAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async modifiersUpdateRaw(requestParameters: ModifiersUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModifierUpdateResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling modifiersUpdate().'
            );
        }

        if (requestParameters['modifierUpdateModel'] == null) {
            throw new runtime.RequiredError(
                'modifierUpdateModel',
                'Required parameter "modifierUpdateModel" was null or undefined when calling modifiersUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/modifiers/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ModifierUpdateModelToJSON(requestParameters['modifierUpdateModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModifierUpdateResponseFromJSON(jsonValue));
    }

    /**
     */
    async modifiersUpdate(requestParameters: ModifiersUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModifierUpdateResponse> {
        const response = await this.modifiersUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
