/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HttpValidationProblemDetails,
  PipeCreateRequest,
  PipeCreateResponse,
  PipeReadAllResponse,
  PipeReadResponse,
  PipeUpdateModel,
  PipeUpdateResponse,
} from '../models/index';
import {
    HttpValidationProblemDetailsFromJSON,
    HttpValidationProblemDetailsToJSON,
    PipeCreateRequestFromJSON,
    PipeCreateRequestToJSON,
    PipeCreateResponseFromJSON,
    PipeCreateResponseToJSON,
    PipeReadAllResponseFromJSON,
    PipeReadAllResponseToJSON,
    PipeReadResponseFromJSON,
    PipeReadResponseToJSON,
    PipeUpdateModelFromJSON,
    PipeUpdateModelToJSON,
    PipeUpdateResponseFromJSON,
    PipeUpdateResponseToJSON,
} from '../models/index';

export interface PipesCreateRequest {
    pipeCreateRequest: PipeCreateRequest;
}

export interface PipesDeleteRequest {
    id: number;
}

export interface PipesReadRequest {
    id: number;
}

export interface PipesUpdateRequest {
    id: number;
    pipeUpdateModel: PipeUpdateModel;
}

/**
 * 
 */
export class PipesApi extends runtime.BaseAPI {

    /**
     */
    async pipesCreateRaw(requestParameters: PipesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PipeCreateResponse>> {
        if (requestParameters['pipeCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'pipeCreateRequest',
                'Required parameter "pipeCreateRequest" was null or undefined when calling pipesCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/pipes`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PipeCreateRequestToJSON(requestParameters['pipeCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PipeCreateResponseFromJSON(jsonValue));
    }

    /**
     */
    async pipesCreate(requestParameters: PipesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PipeCreateResponse> {
        const response = await this.pipesCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async pipesDeleteRaw(requestParameters: PipesDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling pipesDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pipes/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async pipesDelete(requestParameters: PipesDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.pipesDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async pipesReadRaw(requestParameters: PipesReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PipeReadResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling pipesRead().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pipes/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PipeReadResponseFromJSON(jsonValue));
    }

    /**
     */
    async pipesRead(requestParameters: PipesReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PipeReadResponse> {
        const response = await this.pipesReadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async pipesReadAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PipeReadAllResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pipes`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PipeReadAllResponseFromJSON(jsonValue));
    }

    /**
     */
    async pipesReadAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PipeReadAllResponse> {
        const response = await this.pipesReadAllRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async pipesUpdateRaw(requestParameters: PipesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PipeUpdateResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling pipesUpdate().'
            );
        }

        if (requestParameters['pipeUpdateModel'] == null) {
            throw new runtime.RequiredError(
                'pipeUpdateModel',
                'Required parameter "pipeUpdateModel" was null or undefined when calling pipesUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/pipes/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PipeUpdateModelToJSON(requestParameters['pipeUpdateModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PipeUpdateResponseFromJSON(jsonValue));
    }

    /**
     */
    async pipesUpdate(requestParameters: PipesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PipeUpdateResponse> {
        const response = await this.pipesUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
