/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HttpValidationProblemDetails,
  SaleItemCreateRequest,
  SaleItemCreateResponse,
  SaleItemReadAllResponse,
  SaleItemReadResponse,
  SaleItemUpdateModel,
  SaleItemUpdateResponse,
} from '../models/index';
import {
    HttpValidationProblemDetailsFromJSON,
    HttpValidationProblemDetailsToJSON,
    SaleItemCreateRequestFromJSON,
    SaleItemCreateRequestToJSON,
    SaleItemCreateResponseFromJSON,
    SaleItemCreateResponseToJSON,
    SaleItemReadAllResponseFromJSON,
    SaleItemReadAllResponseToJSON,
    SaleItemReadResponseFromJSON,
    SaleItemReadResponseToJSON,
    SaleItemUpdateModelFromJSON,
    SaleItemUpdateModelToJSON,
    SaleItemUpdateResponseFromJSON,
    SaleItemUpdateResponseToJSON,
} from '../models/index';

export interface SaleItemsGetRequest {
    name?: string;
    categoryId?: number;
    page?: number;
    pageSize?: number;
}

export interface SaleItemsIdDeleteRequest {
    id: number;
}

export interface SaleItemsIdPutRequest {
    id: number;
    saleItemUpdateModel: SaleItemUpdateModel;
}

export interface SaleItemsPostRequest {
    saleItemCreateRequest: SaleItemCreateRequest;
}

export interface SaleItemsReadRequest {
    id: number;
}

/**
 * 
 */
export class SaleItemsApi extends runtime.BaseAPI {

    /**
     */
    async saleItemsGetRaw(requestParameters: SaleItemsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SaleItemReadAllResponse>> {
        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['Name'] = requestParameters['name'];
        }

        if (requestParameters['categoryId'] != null) {
            queryParameters['CategoryId'] = requestParameters['categoryId'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['Page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/sale-items`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SaleItemReadAllResponseFromJSON(jsonValue));
    }

    /**
     */
    async saleItemsGet(requestParameters: SaleItemsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SaleItemReadAllResponse> {
        const response = await this.saleItemsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async saleItemsIdDeleteRaw(requestParameters: SaleItemsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling saleItemsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/sale-items/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async saleItemsIdDelete(requestParameters: SaleItemsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.saleItemsIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async saleItemsIdPutRaw(requestParameters: SaleItemsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SaleItemUpdateResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling saleItemsIdPut().'
            );
        }

        if (requestParameters['saleItemUpdateModel'] == null) {
            throw new runtime.RequiredError(
                'saleItemUpdateModel',
                'Required parameter "saleItemUpdateModel" was null or undefined when calling saleItemsIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/sale-items/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SaleItemUpdateModelToJSON(requestParameters['saleItemUpdateModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SaleItemUpdateResponseFromJSON(jsonValue));
    }

    /**
     */
    async saleItemsIdPut(requestParameters: SaleItemsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SaleItemUpdateResponse> {
        const response = await this.saleItemsIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async saleItemsPostRaw(requestParameters: SaleItemsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SaleItemCreateResponse>> {
        if (requestParameters['saleItemCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'saleItemCreateRequest',
                'Required parameter "saleItemCreateRequest" was null or undefined when calling saleItemsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/sale-items`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SaleItemCreateRequestToJSON(requestParameters['saleItemCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SaleItemCreateResponseFromJSON(jsonValue));
    }

    /**
     */
    async saleItemsPost(requestParameters: SaleItemsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SaleItemCreateResponse> {
        const response = await this.saleItemsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async saleItemsReadRaw(requestParameters: SaleItemsReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SaleItemReadResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling saleItemsRead().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/sale-items/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SaleItemReadResponseFromJSON(jsonValue));
    }

    /**
     */
    async saleItemsRead(requestParameters: SaleItemsReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SaleItemReadResponse> {
        const response = await this.saleItemsReadRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
