/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HttpValidationProblemDetails,
  StoreCreateRequest,
  StoreCreateResponse,
  StoreReadAllResponse,
  StoreReadResponse,
  StoreUpdateRequest,
  StoreUpdateResponse,
} from '../models/index';
import {
    HttpValidationProblemDetailsFromJSON,
    HttpValidationProblemDetailsToJSON,
    StoreCreateRequestFromJSON,
    StoreCreateRequestToJSON,
    StoreCreateResponseFromJSON,
    StoreCreateResponseToJSON,
    StoreReadAllResponseFromJSON,
    StoreReadAllResponseToJSON,
    StoreReadResponseFromJSON,
    StoreReadResponseToJSON,
    StoreUpdateRequestFromJSON,
    StoreUpdateRequestToJSON,
    StoreUpdateResponseFromJSON,
    StoreUpdateResponseToJSON,
} from '../models/index';

export interface StoresCreateRequest {
    storeCreateRequest: StoreCreateRequest;
}

export interface StoresDeleteRequest {
    id: number;
}

export interface StoresReadRequest {
    id: number;
}

export interface StoresUpdateRequest {
    id: number;
    storeUpdateRequest: StoreUpdateRequest;
}

/**
 * 
 */
export class StoresApi extends runtime.BaseAPI {

    /**
     */
    async storesCreateRaw(requestParameters: StoresCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StoreCreateResponse>> {
        if (requestParameters['storeCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'storeCreateRequest',
                'Required parameter "storeCreateRequest" was null or undefined when calling storesCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/stores`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StoreCreateRequestToJSON(requestParameters['storeCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StoreCreateResponseFromJSON(jsonValue));
    }

    /**
     */
    async storesCreate(requestParameters: StoresCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StoreCreateResponse> {
        const response = await this.storesCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async storesDeleteRaw(requestParameters: StoresDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling storesDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/stores/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async storesDelete(requestParameters: StoresDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.storesDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async storesReadRaw(requestParameters: StoresReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StoreReadResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling storesRead().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/stores/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StoreReadResponseFromJSON(jsonValue));
    }

    /**
     */
    async storesRead(requestParameters: StoresReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StoreReadResponse> {
        const response = await this.storesReadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async storesReadAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StoreReadAllResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/stores`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StoreReadAllResponseFromJSON(jsonValue));
    }

    /**
     */
    async storesReadAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StoreReadAllResponse> {
        const response = await this.storesReadAllRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async storesUpdateRaw(requestParameters: StoresUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StoreUpdateResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling storesUpdate().'
            );
        }

        if (requestParameters['storeUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'storeUpdateRequest',
                'Required parameter "storeUpdateRequest" was null or undefined when calling storesUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/stores/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: StoreUpdateRequestToJSON(requestParameters['storeUpdateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StoreUpdateResponseFromJSON(jsonValue));
    }

    /**
     */
    async storesUpdate(requestParameters: StoresUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StoreUpdateResponse> {
        const response = await this.storesUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
