/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CashBoxCreateModel
 */
export interface CashBoxCreateModel {
    /**
     * 
     * @type {string}
     * @memberof CashBoxCreateModel
     */
    name: string;
}

/**
 * Check if a given object implements the CashBoxCreateModel interface.
 */
export function instanceOfCashBoxCreateModel(value: object): value is CashBoxCreateModel {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CashBoxCreateModelFromJSON(json: any): CashBoxCreateModel {
    return CashBoxCreateModelFromJSONTyped(json, false);
}

export function CashBoxCreateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CashBoxCreateModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CashBoxCreateModelToJSON(json: any): CashBoxCreateModel {
    return CashBoxCreateModelToJSONTyped(json, false);
}

export function CashBoxCreateModelToJSONTyped(value?: CashBoxCreateModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

