/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CashBoxListModel
 */
export interface CashBoxListModel {
    /**
     * 
     * @type {number}
     * @memberof CashBoxListModel
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof CashBoxListModel
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof CashBoxListModel
     */
    deleted: boolean;
}

/**
 * Check if a given object implements the CashBoxListModel interface.
 */
export function instanceOfCashBoxListModel(value: object): value is CashBoxListModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('deleted' in value) || value['deleted'] === undefined) return false;
    return true;
}

export function CashBoxListModelFromJSON(json: any): CashBoxListModel {
    return CashBoxListModelFromJSONTyped(json, false);
}

export function CashBoxListModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CashBoxListModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'deleted': json['deleted'],
    };
}

export function CashBoxListModelToJSON(json: any): CashBoxListModel {
    return CashBoxListModelToJSONTyped(json, false);
}

export function CashBoxListModelToJSONTyped(value?: CashBoxListModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'deleted': value['deleted'],
    };
}

