/* tslint:disable */
/* eslint-disable */
/**
 * App | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContainerPatchModel
 */
export interface ContainerPatchModel {
    /**
     * 
     * @type {number}
     * @memberof ContainerPatchModel
     */
    pipeId: number | null;
}

/**
 * Check if a given object implements the ContainerPatchModel interface.
 */
export function instanceOfContainerPatchModel(value: object): value is ContainerPatchModel {
    if (!('pipeId' in value) || value['pipeId'] === undefined) return false;
    return true;
}

export function ContainerPatchModelFromJSON(json: any): ContainerPatchModel {
    return ContainerPatchModelFromJSONTyped(json, false);
}

export function ContainerPatchModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerPatchModel {
    if (json == null) {
        return json;
    }
    return {
        
        'pipeId': json['pipeId'],
    };
}

export function ContainerPatchModelToJSON(json: any): ContainerPatchModel {
    return ContainerPatchModelToJSONTyped(json, false);
}

export function ContainerPatchModelToJSONTyped(value?: ContainerPatchModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pipeId': value['pipeId'],
    };
}

