/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CurrencyCreateModel
 */
export interface CurrencyCreateModel {
    /**
     * 
     * @type {string}
     * @memberof CurrencyCreateModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CurrencyCreateModel
     */
    shortName: string;
}

/**
 * Check if a given object implements the CurrencyCreateModel interface.
 */
export function instanceOfCurrencyCreateModel(value: object): value is CurrencyCreateModel {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('shortName' in value) || value['shortName'] === undefined) return false;
    return true;
}

export function CurrencyCreateModelFromJSON(json: any): CurrencyCreateModel {
    return CurrencyCreateModelFromJSONTyped(json, false);
}

export function CurrencyCreateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrencyCreateModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'shortName': json['shortName'],
    };
}

export function CurrencyCreateModelToJSON(json: any): CurrencyCreateModel {
    return CurrencyCreateModelToJSONTyped(json, false);
}

export function CurrencyCreateModelToJSONTyped(value?: CurrencyCreateModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'shortName': value['shortName'],
    };
}

