/* tslint:disable */
/* eslint-disable */
/**
 * App | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompositionListModel } from './CompositionListModel';
import {
    CompositionListModelFromJSON,
    CompositionListModelFromJSONTyped,
    CompositionListModelToJSON,
    CompositionListModelToJSONTyped,
} from './CompositionListModel';
import type { SaleItemListModel } from './SaleItemListModel';
import {
    SaleItemListModelFromJSON,
    SaleItemListModelFromJSONTyped,
    SaleItemListModelToJSON,
    SaleItemListModelToJSONTyped,
} from './SaleItemListModel';
import type { CostListModel } from './CostListModel';
import {
    CostListModelFromJSON,
    CostListModelFromJSONTyped,
    CostListModelToJSON,
    CostListModelToJSONTyped,
} from './CostListModel';

/**
 * 
 * @export
 * @interface ModifierDetailModel
 */
export interface ModifierDetailModel {
    /**
     * 
     * @type {number}
     * @memberof ModifierDetailModel
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ModifierDetailModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ModifierDetailModel
     */
    image: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModifierDetailModel
     */
    showOnWeb: boolean;
    /**
     * 
     * @type {SaleItemListModel}
     * @memberof ModifierDetailModel
     */
    modificationTarget: SaleItemListModel;
    /**
     * 
     * @type {boolean}
     * @memberof ModifierDetailModel
     */
    deleted: boolean;
    /**
     * 
     * @type {Array<CostListModel>}
     * @memberof ModifierDetailModel
     */
    costs: Array<CostListModel>;
    /**
     * 
     * @type {Array<CompositionListModel>}
     * @memberof ModifierDetailModel
     */
    composition: Array<CompositionListModel>;
}

/**
 * Check if a given object implements the ModifierDetailModel interface.
 */
export function instanceOfModifierDetailModel(value: object): value is ModifierDetailModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('showOnWeb' in value) || value['showOnWeb'] === undefined) return false;
    if (!('modificationTarget' in value) || value['modificationTarget'] === undefined) return false;
    if (!('deleted' in value) || value['deleted'] === undefined) return false;
    if (!('costs' in value) || value['costs'] === undefined) return false;
    if (!('composition' in value) || value['composition'] === undefined) return false;
    return true;
}

export function ModifierDetailModelFromJSON(json: any): ModifierDetailModel {
    return ModifierDetailModelFromJSONTyped(json, false);
}

export function ModifierDetailModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModifierDetailModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'image': json['image'],
        'showOnWeb': json['showOnWeb'],
        'modificationTarget': SaleItemListModelFromJSON(json['modificationTarget']),
        'deleted': json['deleted'],
        'costs': ((json['costs'] as Array<any>).map(CostListModelFromJSON)),
        'composition': ((json['composition'] as Array<any>).map(CompositionListModelFromJSON)),
    };
}

export function ModifierDetailModelToJSON(json: any): ModifierDetailModel {
    return ModifierDetailModelToJSONTyped(json, false);
}

export function ModifierDetailModelToJSONTyped(value?: ModifierDetailModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'image': value['image'],
        'showOnWeb': value['showOnWeb'],
        'modificationTarget': SaleItemListModelToJSON(value['modificationTarget']),
        'deleted': value['deleted'],
        'costs': ((value['costs'] as Array<any>).map(CostListModelToJSON)),
        'composition': ((value['composition'] as Array<any>).map(CompositionListModelToJSON)),
    };
}

