/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DiscountUsageListModel } from './DiscountUsageListModel';
import {
    DiscountUsageListModelFromJSON,
    DiscountUsageListModelFromJSONTyped,
    DiscountUsageListModelToJSON,
    DiscountUsageListModelToJSONTyped,
} from './DiscountUsageListModel';
import type { PageMeta } from './PageMeta';
import {
    PageMetaFromJSON,
    PageMetaFromJSONTyped,
    PageMetaToJSON,
    PageMetaToJSONTyped,
} from './PageMeta';

/**
 * 
 * @export
 * @interface PageOfDiscountUsageListModel
 */
export interface PageOfDiscountUsageListModel {
    /**
     * 
     * @type {Array<DiscountUsageListModel>}
     * @memberof PageOfDiscountUsageListModel
     */
    data: Array<DiscountUsageListModel>;
    /**
     * 
     * @type {PageMeta}
     * @memberof PageOfDiscountUsageListModel
     */
    meta: PageMeta;
}

/**
 * Check if a given object implements the PageOfDiscountUsageListModel interface.
 */
export function instanceOfPageOfDiscountUsageListModel(value: object): value is PageOfDiscountUsageListModel {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function PageOfDiscountUsageListModelFromJSON(json: any): PageOfDiscountUsageListModel {
    return PageOfDiscountUsageListModelFromJSONTyped(json, false);
}

export function PageOfDiscountUsageListModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageOfDiscountUsageListModel {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(DiscountUsageListModelFromJSON)),
        'meta': PageMetaFromJSON(json['meta']),
    };
}

export function PageOfDiscountUsageListModelToJSON(json: any): PageOfDiscountUsageListModel {
    return PageOfDiscountUsageListModelToJSONTyped(json, false);
}

export function PageOfDiscountUsageListModelToJSONTyped(value?: PageOfDiscountUsageListModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(DiscountUsageListModelToJSON)),
        'meta': PageMetaToJSON(value['meta']),
    };
}

