/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SaleItemListModel } from './SaleItemListModel';
import {
    SaleItemListModelFromJSON,
    SaleItemListModelFromJSONTyped,
    SaleItemListModelToJSON,
    SaleItemListModelToJSONTyped,
} from './SaleItemListModel';
import type { PageMeta } from './PageMeta';
import {
    PageMetaFromJSON,
    PageMetaFromJSONTyped,
    PageMetaToJSON,
    PageMetaToJSONTyped,
} from './PageMeta';

/**
 * 
 * @export
 * @interface PageOfSaleItemListModel
 */
export interface PageOfSaleItemListModel {
    /**
     * 
     * @type {Array<SaleItemListModel>}
     * @memberof PageOfSaleItemListModel
     */
    data: Array<SaleItemListModel>;
    /**
     * 
     * @type {PageMeta}
     * @memberof PageOfSaleItemListModel
     */
    meta: PageMeta;
}

/**
 * Check if a given object implements the PageOfSaleItemListModel interface.
 */
export function instanceOfPageOfSaleItemListModel(value: object): value is PageOfSaleItemListModel {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function PageOfSaleItemListModelFromJSON(json: any): PageOfSaleItemListModel {
    return PageOfSaleItemListModelFromJSONTyped(json, false);
}

export function PageOfSaleItemListModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageOfSaleItemListModel {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(SaleItemListModelFromJSON)),
        'meta': PageMetaFromJSON(json['meta']),
    };
}

export function PageOfSaleItemListModelToJSON(json: any): PageOfSaleItemListModel {
    return PageOfSaleItemListModelToJSONTyped(json, false);
}

export function PageOfSaleItemListModelToJSONTyped(value?: PageOfSaleItemListModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(SaleItemListModelToJSON)),
        'meta': PageMetaToJSON(value['meta']),
    };
}

