/* tslint:disable */
/* eslint-disable */
/**
 * App | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PipeListModel2
 */
export interface PipeListModel2 {
    /**
     * 
     * @type {number}
     * @memberof PipeListModel2
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PipeListModel2
     */
    name: string;
}

/**
 * Check if a given object implements the PipeListModel2 interface.
 */
export function instanceOfPipeListModel2(value: object): value is PipeListModel2 {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function PipeListModel2FromJSON(json: any): PipeListModel2 {
    return PipeListModel2FromJSONTyped(json, false);
}

export function PipeListModel2FromJSONTyped(json: any, ignoreDiscriminator: boolean): PipeListModel2 {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function PipeListModel2ToJSON(json: any): PipeListModel2 {
    return PipeListModel2ToJSONTyped(json, false);
}

export function PipeListModel2ToJSONTyped(value?: PipeListModel2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

