/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserListModel } from './UserListModel';
import {
    UserListModelFromJSON,
    UserListModelFromJSONTyped,
    UserListModelToJSON,
    UserListModelToJSONTyped,
} from './UserListModel';

/**
 * 
 * @export
 * @interface SaleTransactionListModel
 */
export interface SaleTransactionListModel {
    /**
     * 
     * @type {number}
     * @memberof SaleTransactionListModel
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof SaleTransactionListModel
     */
    note: string | null;
    /**
     * 
     * @type {UserListModel}
     * @memberof SaleTransactionListModel
     */
    responsibleUser: UserListModel;
    /**
     * 
     * @type {Date}
     * @memberof SaleTransactionListModel
     */
    timestamp: Date;
    /**
     * 
     * @type {boolean}
     * @memberof SaleTransactionListModel
     */
    cancelled: boolean;
}

/**
 * Check if a given object implements the SaleTransactionListModel interface.
 */
export function instanceOfSaleTransactionListModel(value: object): value is SaleTransactionListModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('note' in value) || value['note'] === undefined) return false;
    if (!('responsibleUser' in value) || value['responsibleUser'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('cancelled' in value) || value['cancelled'] === undefined) return false;
    return true;
}

export function SaleTransactionListModelFromJSON(json: any): SaleTransactionListModel {
    return SaleTransactionListModelFromJSONTyped(json, false);
}

export function SaleTransactionListModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaleTransactionListModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'note': json['note'],
        'responsibleUser': UserListModelFromJSON(json['responsibleUser']),
        'timestamp': (new Date(json['timestamp'])),
        'cancelled': json['cancelled'],
    };
}

export function SaleTransactionListModelToJSON(json: any): SaleTransactionListModel {
    return SaleTransactionListModelToJSONTyped(json, false);
}

export function SaleTransactionListModelToJSONTyped(value?: SaleTransactionListModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'note': value['note'],
        'responsibleUser': UserListModelToJSON(value['responsibleUser']),
        'timestamp': ((value['timestamp']).toISOString()),
        'cancelled': value['cancelled'],
    };
}

