/* tslint:disable */
/* eslint-disable */
/**
 * App | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModifierAmountCreateModel } from './ModifierAmountCreateModel';
import {
    ModifierAmountCreateModelFromJSON,
    ModifierAmountCreateModelFromJSONTyped,
    ModifierAmountCreateModelToJSON,
    ModifierAmountCreateModelToJSONTyped,
} from './ModifierAmountCreateModel';

/**
 * 
 * @export
 * @interface SaleTransactionItemCreateModel
 */
export interface SaleTransactionItemCreateModel {
    /**
     * 
     * @type {number}
     * @memberof SaleTransactionItemCreateModel
     */
    saleItemId: number;
    /**
     * 
     * @type {Array<ModifierAmountCreateModel>}
     * @memberof SaleTransactionItemCreateModel
     */
    modifierAmounts: Array<ModifierAmountCreateModel>;
    /**
     * 
     * @type {number}
     * @memberof SaleTransactionItemCreateModel
     */
    itemAmount: number;
    /**
     * 
     * @type {number}
     * @memberof SaleTransactionItemCreateModel
     */
    storeId: number | null;
}

/**
 * Check if a given object implements the SaleTransactionItemCreateModel interface.
 */
export function instanceOfSaleTransactionItemCreateModel(value: object): value is SaleTransactionItemCreateModel {
    if (!('saleItemId' in value) || value['saleItemId'] === undefined) return false;
    if (!('modifierAmounts' in value) || value['modifierAmounts'] === undefined) return false;
    if (!('itemAmount' in value) || value['itemAmount'] === undefined) return false;
    if (!('storeId' in value) || value['storeId'] === undefined) return false;
    return true;
}

export function SaleTransactionItemCreateModelFromJSON(json: any): SaleTransactionItemCreateModel {
    return SaleTransactionItemCreateModelFromJSONTyped(json, false);
}

export function SaleTransactionItemCreateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaleTransactionItemCreateModel {
    if (json == null) {
        return json;
    }
    return {
        
        'saleItemId': json['saleItemId'],
        'modifierAmounts': ((json['modifierAmounts'] as Array<any>).map(ModifierAmountCreateModelFromJSON)),
        'itemAmount': json['itemAmount'],
        'storeId': json['storeId'],
    };
}

export function SaleTransactionItemCreateModelToJSON(json: any): SaleTransactionItemCreateModel {
    return SaleTransactionItemCreateModelToJSONTyped(json, false);
}

export function SaleTransactionItemCreateModelToJSONTyped(value?: SaleTransactionItemCreateModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'saleItemId': value['saleItemId'],
        'modifierAmounts': ((value['modifierAmounts'] as Array<any>).map(ModifierAmountCreateModelToJSON)),
        'itemAmount': value['itemAmount'],
        'storeId': value['storeId'],
    };
}

