/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SaleItemListModel } from './SaleItemListModel';
import {
    SaleItemListModelFromJSON,
    SaleItemListModelFromJSONTyped,
    SaleItemListModelToJSON,
    SaleItemListModelToJSONTyped,
} from './SaleItemListModel';
import type { TransactionPriceListModel } from './TransactionPriceListModel';
import {
    TransactionPriceListModelFromJSON,
    TransactionPriceListModelFromJSONTyped,
    TransactionPriceListModelToJSON,
    TransactionPriceListModelToJSONTyped,
} from './TransactionPriceListModel';
import type { ModifierAmountListModel } from './ModifierAmountListModel';
import {
    ModifierAmountListModelFromJSON,
    ModifierAmountListModelFromJSONTyped,
    ModifierAmountListModelToJSON,
    ModifierAmountListModelToJSONTyped,
} from './ModifierAmountListModel';

/**
 * 
 * @export
 * @interface SaleTransactionItemListModel
 */
export interface SaleTransactionItemListModel {
    /**
     * 
     * @type {number}
     * @memberof SaleTransactionItemListModel
     */
    id: number;
    /**
     * 
     * @type {SaleItemListModel}
     * @memberof SaleTransactionItemListModel
     */
    saleItem: SaleItemListModel;
    /**
     * 
     * @type {Array<ModifierAmountListModel>}
     * @memberof SaleTransactionItemListModel
     */
    modifierAmounts: Array<ModifierAmountListModel>;
    /**
     * 
     * @type {Array<TransactionPriceListModel>}
     * @memberof SaleTransactionItemListModel
     */
    transactionPrices: Array<TransactionPriceListModel>;
    /**
     * 
     * @type {number}
     * @memberof SaleTransactionItemListModel
     */
    itemAmount: number;
    /**
     * 
     * @type {boolean}
     * @memberof SaleTransactionItemListModel
     */
    cancelled: boolean;
}

/**
 * Check if a given object implements the SaleTransactionItemListModel interface.
 */
export function instanceOfSaleTransactionItemListModel(value: object): value is SaleTransactionItemListModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('saleItem' in value) || value['saleItem'] === undefined) return false;
    if (!('modifierAmounts' in value) || value['modifierAmounts'] === undefined) return false;
    if (!('transactionPrices' in value) || value['transactionPrices'] === undefined) return false;
    if (!('itemAmount' in value) || value['itemAmount'] === undefined) return false;
    if (!('cancelled' in value) || value['cancelled'] === undefined) return false;
    return true;
}

export function SaleTransactionItemListModelFromJSON(json: any): SaleTransactionItemListModel {
    return SaleTransactionItemListModelFromJSONTyped(json, false);
}

export function SaleTransactionItemListModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaleTransactionItemListModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'saleItem': SaleItemListModelFromJSON(json['saleItem']),
        'modifierAmounts': ((json['modifierAmounts'] as Array<any>).map(ModifierAmountListModelFromJSON)),
        'transactionPrices': ((json['transactionPrices'] as Array<any>).map(TransactionPriceListModelFromJSON)),
        'itemAmount': json['itemAmount'],
        'cancelled': json['cancelled'],
    };
}

export function SaleTransactionItemListModelToJSON(json: any): SaleTransactionItemListModel {
    return SaleTransactionItemListModelToJSONTyped(json, false);
}

export function SaleTransactionItemListModelToJSONTyped(value?: SaleTransactionItemListModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'saleItem': SaleItemListModelToJSON(value['saleItem']),
        'modifierAmounts': ((value['modifierAmounts'] as Array<any>).map(ModifierAmountListModelToJSON)),
        'transactionPrices': ((value['transactionPrices'] as Array<any>).map(TransactionPriceListModelToJSON)),
        'itemAmount': value['itemAmount'],
        'cancelled': value['cancelled'],
    };
}

