/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SaleTransactionListModel2 } from './SaleTransactionListModel2';
import {
    SaleTransactionListModel2FromJSON,
    SaleTransactionListModel2FromJSONTyped,
    SaleTransactionListModel2ToJSON,
    SaleTransactionListModel2ToJSONTyped,
} from './SaleTransactionListModel2';
import type { StoreTransactionItemListModel } from './StoreTransactionItemListModel';
import {
    StoreTransactionItemListModelFromJSON,
    StoreTransactionItemListModelFromJSONTyped,
    StoreTransactionItemListModelToJSON,
    StoreTransactionItemListModelToJSONTyped,
} from './StoreTransactionItemListModel';
import type { UserListModel } from './UserListModel';
import {
    UserListModelFromJSON,
    UserListModelFromJSONTyped,
    UserListModelToJSON,
    UserListModelToJSONTyped,
} from './UserListModel';

/**
 * 
 * @export
 * @interface StoreTransactionDetailModel
 */
export interface StoreTransactionDetailModel {
    /**
     * 
     * @type {number}
     * @memberof StoreTransactionDetailModel
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof StoreTransactionDetailModel
     */
    note: string | null;
    /**
     * 
     * @type {UserListModel}
     * @memberof StoreTransactionDetailModel
     */
    responsibleUser: UserListModel;
    /**
     * 
     * @type {Date}
     * @memberof StoreTransactionDetailModel
     */
    timestamp: Date;
    /**
     * 
     * @type {boolean}
     * @memberof StoreTransactionDetailModel
     */
    cancelled: boolean;
    /**
     * 
     * @type {number}
     * @memberof StoreTransactionDetailModel
     */
    transactionReason: number;
    /**
     * 
     * @type {SaleTransactionListModel2}
     * @memberof StoreTransactionDetailModel
     */
    saleTransaction: SaleTransactionListModel2 | null;
    /**
     * 
     * @type {Array<StoreTransactionItemListModel>}
     * @memberof StoreTransactionDetailModel
     */
    storeTransactionItems: Array<StoreTransactionItemListModel>;
}

/**
 * Check if a given object implements the StoreTransactionDetailModel interface.
 */
export function instanceOfStoreTransactionDetailModel(value: object): value is StoreTransactionDetailModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('note' in value) || value['note'] === undefined) return false;
    if (!('responsibleUser' in value) || value['responsibleUser'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('cancelled' in value) || value['cancelled'] === undefined) return false;
    if (!('transactionReason' in value) || value['transactionReason'] === undefined) return false;
    if (!('saleTransaction' in value) || value['saleTransaction'] === undefined) return false;
    if (!('storeTransactionItems' in value) || value['storeTransactionItems'] === undefined) return false;
    return true;
}

export function StoreTransactionDetailModelFromJSON(json: any): StoreTransactionDetailModel {
    return StoreTransactionDetailModelFromJSONTyped(json, false);
}

export function StoreTransactionDetailModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreTransactionDetailModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'note': json['note'],
        'responsibleUser': UserListModelFromJSON(json['responsibleUser']),
        'timestamp': (new Date(json['timestamp'])),
        'cancelled': json['cancelled'],
        'transactionReason': json['transactionReason'],
        'saleTransaction': SaleTransactionListModel2FromJSON(json['saleTransaction']),
        'storeTransactionItems': ((json['storeTransactionItems'] as Array<any>).map(StoreTransactionItemListModelFromJSON)),
    };
}

export function StoreTransactionDetailModelToJSON(json: any): StoreTransactionDetailModel {
    return StoreTransactionDetailModelToJSONTyped(json, false);
}

export function StoreTransactionDetailModelToJSONTyped(value?: StoreTransactionDetailModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'note': value['note'],
        'responsibleUser': UserListModelToJSON(value['responsibleUser']),
        'timestamp': ((value['timestamp']).toISOString()),
        'cancelled': value['cancelled'],
        'transactionReason': value['transactionReason'],
        'saleTransaction': SaleTransactionListModel2ToJSON(value['saleTransaction']),
        'storeTransactionItems': ((value['storeTransactionItems'] as Array<any>).map(StoreTransactionItemListModelToJSON)),
    };
}

