/* tslint:disable */
/* eslint-disable */
/**
 * App | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryListModel } from './CategoryListModel';
import {
    CategoryListModelFromJSON,
    CategoryListModelFromJSONTyped,
    CategoryListModelToJSON,
    CategoryListModelToJSONTyped,
} from './CategoryListModel';
import type { CostListModel } from './CostListModel';
import {
    CostListModelFromJSON,
    CostListModelFromJSONTyped,
    CostListModelToJSON,
    CostListModelToJSONTyped,
} from './CostListModel';

/**
 * 
 * @export
 * @interface StoreItemDetailModel
 */
export interface StoreItemDetailModel {
    /**
     * 
     * @type {number}
     * @memberof StoreItemDetailModel
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof StoreItemDetailModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof StoreItemDetailModel
     */
    image: string;
    /**
     * 
     * @type {boolean}
     * @memberof StoreItemDetailModel
     */
    deleted: boolean;
    /**
     * 
     * @type {string}
     * @memberof StoreItemDetailModel
     */
    unitName: string;
    /**
     * 
     * @type {boolean}
     * @memberof StoreItemDetailModel
     */
    barmanCanStock: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof StoreItemDetailModel
     */
    isContainerItem: boolean;
    /**
     * 
     * @type {Array<CategoryListModel>}
     * @memberof StoreItemDetailModel
     */
    categories: Array<CategoryListModel>;
    /**
     * 
     * @type {Array<CostListModel>}
     * @memberof StoreItemDetailModel
     */
    costs: Array<CostListModel>;
}

/**
 * Check if a given object implements the StoreItemDetailModel interface.
 */
export function instanceOfStoreItemDetailModel(value: object): value is StoreItemDetailModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('deleted' in value) || value['deleted'] === undefined) return false;
    if (!('unitName' in value) || value['unitName'] === undefined) return false;
    if (!('barmanCanStock' in value) || value['barmanCanStock'] === undefined) return false;
    if (!('isContainerItem' in value) || value['isContainerItem'] === undefined) return false;
    if (!('categories' in value) || value['categories'] === undefined) return false;
    if (!('costs' in value) || value['costs'] === undefined) return false;
    return true;
}

export function StoreItemDetailModelFromJSON(json: any): StoreItemDetailModel {
    return StoreItemDetailModelFromJSONTyped(json, false);
}

export function StoreItemDetailModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreItemDetailModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'image': json['image'],
        'deleted': json['deleted'],
        'unitName': json['unitName'],
        'barmanCanStock': json['barmanCanStock'],
        'isContainerItem': json['isContainerItem'],
        'categories': ((json['categories'] as Array<any>).map(CategoryListModelFromJSON)),
        'costs': ((json['costs'] as Array<any>).map(CostListModelFromJSON)),
    };
}

export function StoreItemDetailModelToJSON(json: any): StoreItemDetailModel {
    return StoreItemDetailModelToJSONTyped(json, false);
}

export function StoreItemDetailModelToJSONTyped(value?: StoreItemDetailModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'image': value['image'],
        'deleted': value['deleted'],
        'unitName': value['unitName'],
        'barmanCanStock': value['barmanCanStock'],
        'isContainerItem': value['isContainerItem'],
        'categories': ((value['categories'] as Array<any>).map(CategoryListModelToJSON)),
        'costs': ((value['costs'] as Array<any>).map(CostListModelToJSON)),
    };
}

