/* tslint:disable */
/* eslint-disable */
/**
 * App | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StoreCreateModel
 */
export interface StoreCreateModel {
    /**
     * 
     * @type {string}
     * @memberof StoreCreateModel
     */
    name: string;
}

/**
 * Check if a given object implements the StoreCreateModel interface.
 */
export function instanceOfStoreCreateModel(value: object): value is StoreCreateModel {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function StoreCreateModelFromJSON(json: any): StoreCreateModel {
    return StoreCreateModelFromJSONTyped(json, false);
}

export function StoreCreateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreCreateModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function StoreCreateModelToJSON(json: any): StoreCreateModel {
    return StoreCreateModelToJSONTyped(json, false);
}

export function StoreCreateModelToJSONTyped(value?: StoreCreateModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

