/* tslint:disable */
/* eslint-disable */
/**
 * App | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CurrencyListModel } from './CurrencyListModel';
import {
    CurrencyListModelFromJSON,
    CurrencyListModelFromJSONTyped,
    CurrencyListModelToJSON,
    CurrencyListModelToJSONTyped,
} from './CurrencyListModel';

/**
 * 
 * @export
 * @interface TransactionPriceListModel
 */
export interface TransactionPriceListModel {
    /**
     * 
     * @type {CurrencyListModel}
     * @memberof TransactionPriceListModel
     */
    currency: CurrencyListModel;
    /**
     * 
     * @type {number}
     * @memberof TransactionPriceListModel
     */
    saleTransactionItemId: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionPriceListModel
     */
    amount: number;
    /**
     * 
     * @type {boolean}
     * @memberof TransactionPriceListModel
     */
    cancelled: boolean;
}

/**
 * Check if a given object implements the TransactionPriceListModel interface.
 */
export function instanceOfTransactionPriceListModel(value: object): value is TransactionPriceListModel {
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('saleTransactionItemId' in value) || value['saleTransactionItemId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('cancelled' in value) || value['cancelled'] === undefined) return false;
    return true;
}

export function TransactionPriceListModelFromJSON(json: any): TransactionPriceListModel {
    return TransactionPriceListModelFromJSONTyped(json, false);
}

export function TransactionPriceListModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionPriceListModel {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': CurrencyListModelFromJSON(json['currency']),
        'saleTransactionItemId': json['saleTransactionItemId'],
        'amount': json['amount'],
        'cancelled': json['cancelled'],
    };
}

export function TransactionPriceListModelToJSON(json: any): TransactionPriceListModel {
    return TransactionPriceListModelToJSONTyped(json, false);
}

export function TransactionPriceListModelToJSONTyped(value?: TransactionPriceListModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': CurrencyListModelToJSON(value['currency']),
        'saleTransactionItemId': value['saleTransactionItemId'],
        'amount': value['amount'],
        'cancelled': value['cancelled'],
    };
}

