/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserDetailModel
 */
export interface UserDetailModel {
    /**
     * 
     * @type {number}
     * @memberof UserDetailModel
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserDetailModel
     */
    userName: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserDetailModel
     */
    deleted: boolean;
}

/**
 * Check if a given object implements the UserDetailModel interface.
 */
export function instanceOfUserDetailModel(value: object): value is UserDetailModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userName' in value) || value['userName'] === undefined) return false;
    if (!('deleted' in value) || value['deleted'] === undefined) return false;
    return true;
}

export function UserDetailModelFromJSON(json: any): UserDetailModel {
    return UserDetailModelFromJSONTyped(json, false);
}

export function UserDetailModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDetailModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userName': json['userName'],
        'deleted': json['deleted'],
    };
}

export function UserDetailModelToJSON(json: any): UserDetailModel {
    return UserDetailModelToJSONTyped(json, false);
}

export function UserDetailModelToJSONTyped(value?: UserDetailModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userName': value['userName'],
        'deleted': value['deleted'],
    };
}

