/* tslint:disable */
/* eslint-disable */
/**
 * App | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HttpValidationProblemDetails,
  PageOfStoreItemAmountListModel,
} from '../models/index';
import {
    HttpValidationProblemDetailsFromJSON,
    HttpValidationProblemDetailsToJSON,
    PageOfStoreItemAmountListModelFromJSON,
    PageOfStoreItemAmountListModelToJSON,
} from '../models/index';

export interface SaleItemAmountsGetRequest {
    storeId: number;
    page?: number;
    pageSize?: number;
    categoryId?: number;
}

/**
 * 
 */
export class SaleItemAmountsApi extends runtime.BaseAPI {

    /**
     */
    async saleItemAmountsGetRaw(requestParameters: SaleItemAmountsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PageOfStoreItemAmountListModel>> {
        if (requestParameters['storeId'] == null) {
            throw new runtime.RequiredError(
                'storeId',
                'Required parameter "storeId" was null or undefined when calling saleItemAmountsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['storeId'] != null) {
            queryParameters['storeId'] = requestParameters['storeId'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['categoryId'] != null) {
            queryParameters['categoryId'] = requestParameters['categoryId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/sale-item-amounts`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PageOfStoreItemAmountListModelFromJSON(jsonValue));
    }

    /**
     */
    async saleItemAmountsGet(requestParameters: SaleItemAmountsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PageOfStoreItemAmountListModel> {
        const response = await this.saleItemAmountsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
