/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AccountTransactionType = {
    SaleMoney: 'SaleMoney',
    DonationMoney: 'DonationMoney',
    Prestige: 'Prestige'
} as const;
export type AccountTransactionType = typeof AccountTransactionType[keyof typeof AccountTransactionType];


export function instanceOfAccountTransactionType(value: any): boolean {
    for (const key in AccountTransactionType) {
        if (Object.prototype.hasOwnProperty.call(AccountTransactionType, key)) {
            if (AccountTransactionType[key as keyof typeof AccountTransactionType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AccountTransactionTypeFromJSON(json: any): AccountTransactionType {
    return AccountTransactionTypeFromJSONTyped(json, false);
}

export function AccountTransactionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountTransactionType {
    return json as AccountTransactionType;
}

export function AccountTransactionTypeToJSON(value?: AccountTransactionType | null): any {
    return value as any;
}

export function AccountTransactionTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): AccountTransactionType {
    return value as AccountTransactionType;
}

