/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountTransactionType } from './AccountTransactionType';
import {
    AccountTransactionTypeFromJSON,
    AccountTransactionTypeFromJSONTyped,
    AccountTransactionTypeToJSON,
    AccountTransactionTypeToJSONTyped,
} from './AccountTransactionType';

/**
 * 
 * @export
 * @interface AccountTransactionModel
 */
export interface AccountTransactionModel {
    /**
     * 
     * @type {string}
     * @memberof AccountTransactionModel
     */
    amount: string;
    /**
     * 
     * @type {number}
     * @memberof AccountTransactionModel
     */
    saleTransactionId: number;
    /**
     * 
     * @type {Date}
     * @memberof AccountTransactionModel
     */
    timestamp: Date;
    /**
     * 
     * @type {AccountTransactionType}
     * @memberof AccountTransactionModel
     */
    type: AccountTransactionType;
}



/**
 * Check if a given object implements the AccountTransactionModel interface.
 */
export function instanceOfAccountTransactionModel(value: object): value is AccountTransactionModel {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('saleTransactionId' in value) || value['saleTransactionId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function AccountTransactionModelFromJSON(json: any): AccountTransactionModel {
    return AccountTransactionModelFromJSONTyped(json, false);
}

export function AccountTransactionModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountTransactionModel {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'saleTransactionId': json['saleTransactionId'],
        'timestamp': (new Date(json['timestamp'])),
        'type': AccountTransactionTypeFromJSON(json['type']),
    };
}

export function AccountTransactionModelToJSON(json: any): AccountTransactionModel {
    return AccountTransactionModelToJSONTyped(json, false);
}

export function AccountTransactionModelToJSONTyped(value?: AccountTransactionModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'saleTransactionId': value['saleTransactionId'],
        'timestamp': value['timestamp'].toISOString(),
        'type': AccountTransactionTypeToJSON(value['type']),
    };
}

