/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountTransactionReadAllResponse } from './AccountTransactionReadAllResponse';
import {
    AccountTransactionReadAllResponseFromJSON,
    AccountTransactionReadAllResponseFromJSONTyped,
    AccountTransactionReadAllResponseToJSON,
    AccountTransactionReadAllResponseToJSONTyped,
} from './AccountTransactionReadAllResponse';
import type { CashBoxesReadIdParameter } from './CashBoxesReadIdParameter';
import {
    CashBoxesReadIdParameterFromJSON,
    CashBoxesReadIdParameterFromJSONTyped,
    CashBoxesReadIdParameterToJSON,
    CashBoxesReadIdParameterToJSONTyped,
} from './CashBoxesReadIdParameter';

/**
 * 
 * @export
 * @interface CashBoxReadResponse
 */
export interface CashBoxReadResponse {
    /**
     * 
     * @type {CashBoxesReadIdParameter}
     * @memberof CashBoxReadResponse
     */
    id: CashBoxesReadIdParameter;
    /**
     * 
     * @type {string}
     * @memberof CashBoxReadResponse
     */
    name: string;
    /**
     * 
     * @type {AccountTransactionReadAllResponse}
     * @memberof CashBoxReadResponse
     */
    salesTransactions: AccountTransactionReadAllResponse;
    /**
     * 
     * @type {AccountTransactionReadAllResponse}
     * @memberof CashBoxReadResponse
     */
    donationsTransactions: AccountTransactionReadAllResponse;
    /**
     * 
     * @type {Array<Date>}
     * @memberof CashBoxReadResponse
     */
    stockTakings: Array<Date>;
}

/**
 * Check if a given object implements the CashBoxReadResponse interface.
 */
export function instanceOfCashBoxReadResponse(value: object): value is CashBoxReadResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('salesTransactions' in value) || value['salesTransactions'] === undefined) return false;
    if (!('donationsTransactions' in value) || value['donationsTransactions'] === undefined) return false;
    if (!('stockTakings' in value) || value['stockTakings'] === undefined) return false;
    return true;
}

export function CashBoxReadResponseFromJSON(json: any): CashBoxReadResponse {
    return CashBoxReadResponseFromJSONTyped(json, false);
}

export function CashBoxReadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CashBoxReadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': CashBoxesReadIdParameterFromJSON(json['id']),
        'name': json['name'],
        'salesTransactions': AccountTransactionReadAllResponseFromJSON(json['salesTransactions']),
        'donationsTransactions': AccountTransactionReadAllResponseFromJSON(json['donationsTransactions']),
        'stockTakings': json['stockTakings'],
    };
}

export function CashBoxReadResponseToJSON(json: any): CashBoxReadResponse {
    return CashBoxReadResponseToJSONTyped(json, false);
}

export function CashBoxReadResponseToJSONTyped(value?: CashBoxReadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': CashBoxesReadIdParameterToJSON(value['id']),
        'name': value['name'],
        'salesTransactions': AccountTransactionReadAllResponseToJSON(value['salesTransactions']),
        'donationsTransactions': AccountTransactionReadAllResponseToJSON(value['donationsTransactions']),
        'stockTakings': value['stockTakings'],
    };
}

