/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CashBoxesReadIdParameter } from './CashBoxesReadIdParameter';
import {
    CashBoxesReadIdParameterFromJSON,
    CashBoxesReadIdParameterFromJSONTyped,
    CashBoxesReadIdParameterToJSON,
    CashBoxesReadIdParameterToJSONTyped,
} from './CashBoxesReadIdParameter';
import type { AccountTransactionModelAmount } from './AccountTransactionModelAmount';
import {
    AccountTransactionModelAmountFromJSON,
    AccountTransactionModelAmountFromJSONTyped,
    AccountTransactionModelAmountToJSON,
    AccountTransactionModelAmountToJSONTyped,
} from './AccountTransactionModelAmount';

/**
 * 
 * @export
 * @interface CompositeAmountModel
 */
export interface CompositeAmountModel {
    /**
     * 
     * @type {AccountTransactionModelAmount}
     * @memberof CompositeAmountModel
     */
    amount: AccountTransactionModelAmount;
    /**
     * 
     * @type {CashBoxesReadIdParameter}
     * @memberof CompositeAmountModel
     */
    compositeId: CashBoxesReadIdParameter;
    /**
     * 
     * @type {CashBoxesReadIdParameter}
     * @memberof CompositeAmountModel
     */
    storeId: CashBoxesReadIdParameter;
}

/**
 * Check if a given object implements the CompositeAmountModel interface.
 */
export function instanceOfCompositeAmountModel(value: object): value is CompositeAmountModel {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('compositeId' in value) || value['compositeId'] === undefined) return false;
    if (!('storeId' in value) || value['storeId'] === undefined) return false;
    return true;
}

export function CompositeAmountModelFromJSON(json: any): CompositeAmountModel {
    return CompositeAmountModelFromJSONTyped(json, false);
}

export function CompositeAmountModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompositeAmountModel {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': AccountTransactionModelAmountFromJSON(json['amount']),
        'compositeId': CashBoxesReadIdParameterFromJSON(json['compositeId']),
        'storeId': CashBoxesReadIdParameterFromJSON(json['storeId']),
    };
}

export function CompositeAmountModelToJSON(json: any): CompositeAmountModel {
    return CompositeAmountModelToJSONTyped(json, false);
}

export function CompositeAmountModelToJSONTyped(value?: CompositeAmountModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': AccountTransactionModelAmountToJSON(value['amount']),
        'compositeId': CashBoxesReadIdParameterToJSON(value['compositeId']),
        'storeId': CashBoxesReadIdParameterToJSON(value['storeId']),
    };
}

