/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMeta } from './PageMeta';
import {
    PageMetaFromJSON,
    PageMetaFromJSONTyped,
    PageMetaToJSON,
    PageMetaToJSONTyped,
} from './PageMeta';
import type { ContainerListModel } from './ContainerListModel';
import {
    ContainerListModelFromJSON,
    ContainerListModelFromJSONTyped,
    ContainerListModelToJSON,
    ContainerListModelToJSONTyped,
} from './ContainerListModel';

/**
 * 
 * @export
 * @interface ContainerReadAllResponse
 */
export interface ContainerReadAllResponse {
    /**
     * 
     * @type {Array<ContainerListModel>}
     * @memberof ContainerReadAllResponse
     */
    data: Array<ContainerListModel>;
    /**
     * 
     * @type {PageMeta}
     * @memberof ContainerReadAllResponse
     */
    meta: PageMeta;
}

/**
 * Check if a given object implements the ContainerReadAllResponse interface.
 */
export function instanceOfContainerReadAllResponse(value: object): value is ContainerReadAllResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ContainerReadAllResponseFromJSON(json: any): ContainerReadAllResponse {
    return ContainerReadAllResponseFromJSONTyped(json, false);
}

export function ContainerReadAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerReadAllResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ContainerListModelFromJSON)),
        'meta': PageMetaFromJSON(json['meta']),
    };
}

export function ContainerReadAllResponseToJSON(json: any): ContainerReadAllResponse {
    return ContainerReadAllResponseToJSONTyped(json, false);
}

export function ContainerReadAllResponseToJSONTyped(value?: ContainerReadAllResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ContainerListModelToJSON)),
        'meta': PageMetaToJSON(value['meta']),
    };
}

