/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CashBoxesReadIdParameter } from './CashBoxesReadIdParameter';
import {
    CashBoxesReadIdParameterFromJSON,
    CashBoxesReadIdParameterFromJSONTyped,
    CashBoxesReadIdParameterToJSON,
    CashBoxesReadIdParameterToJSONTyped,
} from './CashBoxesReadIdParameter';
import type { ContainerCreateRequestCost } from './ContainerCreateRequestCost';
import {
    ContainerCreateRequestCostFromJSON,
    ContainerCreateRequestCostFromJSONTyped,
    ContainerCreateRequestCostToJSON,
    ContainerCreateRequestCostToJSONTyped,
} from './ContainerCreateRequestCost';

/**
 * 
 * @export
 * @interface ContainerTemplateCreateRequest
 */
export interface ContainerTemplateCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof ContainerTemplateCreateRequest
     */
    name: string;
    /**
     * 
     * @type {ContainerCreateRequestCost}
     * @memberof ContainerTemplateCreateRequest
     */
    amount: ContainerCreateRequestCost;
    /**
     * 
     * @type {CashBoxesReadIdParameter}
     * @memberof ContainerTemplateCreateRequest
     */
    storeItemId: CashBoxesReadIdParameter;
}

/**
 * Check if a given object implements the ContainerTemplateCreateRequest interface.
 */
export function instanceOfContainerTemplateCreateRequest(value: object): value is ContainerTemplateCreateRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('storeItemId' in value) || value['storeItemId'] === undefined) return false;
    return true;
}

export function ContainerTemplateCreateRequestFromJSON(json: any): ContainerTemplateCreateRequest {
    return ContainerTemplateCreateRequestFromJSONTyped(json, false);
}

export function ContainerTemplateCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerTemplateCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'amount': ContainerCreateRequestCostFromJSON(json['amount']),
        'storeItemId': CashBoxesReadIdParameterFromJSON(json['storeItemId']),
    };
}

export function ContainerTemplateCreateRequestToJSON(json: any): ContainerTemplateCreateRequest {
    return ContainerTemplateCreateRequestToJSONTyped(json, false);
}

export function ContainerTemplateCreateRequestToJSONTyped(value?: ContainerTemplateCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'amount': ContainerCreateRequestCostToJSON(value['amount']),
        'storeItemId': CashBoxesReadIdParameterToJSON(value['storeItemId']),
    };
}

