/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContainerTemplateUpdateRequestModel
 */
export interface ContainerTemplateUpdateRequestModel {
    /**
     * 
     * @type {string}
     * @memberof ContainerTemplateUpdateRequestModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerTemplateUpdateRequestModel
     */
    amount: string;
    /**
     * 
     * @type {number}
     * @memberof ContainerTemplateUpdateRequestModel
     */
    storeItemId: number;
}

/**
 * Check if a given object implements the ContainerTemplateUpdateRequestModel interface.
 */
export function instanceOfContainerTemplateUpdateRequestModel(value: object): value is ContainerTemplateUpdateRequestModel {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('storeItemId' in value) || value['storeItemId'] === undefined) return false;
    return true;
}

export function ContainerTemplateUpdateRequestModelFromJSON(json: any): ContainerTemplateUpdateRequestModel {
    return ContainerTemplateUpdateRequestModelFromJSONTyped(json, false);
}

export function ContainerTemplateUpdateRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerTemplateUpdateRequestModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'amount': json['amount'],
        'storeItemId': json['storeItemId'],
    };
}

export function ContainerTemplateUpdateRequestModelToJSON(json: any): ContainerTemplateUpdateRequestModel {
    return ContainerTemplateUpdateRequestModelToJSONTyped(json, false);
}

export function ContainerTemplateUpdateRequestModelToJSONTyped(value?: ContainerTemplateUpdateRequestModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'amount': value['amount'],
        'storeItemId': value['storeItemId'],
    };
}

