/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CashBoxesReadIdParameter } from './CashBoxesReadIdParameter';
import {
    CashBoxesReadIdParameterFromJSON,
    CashBoxesReadIdParameterFromJSONTyped,
    CashBoxesReadIdParameterToJSON,
    CashBoxesReadIdParameterToJSONTyped,
} from './CashBoxesReadIdParameter';
import type { UserListModel } from './UserListModel';
import {
    UserListModelFromJSON,
    UserListModelFromJSONTyped,
    UserListModelToJSON,
    UserListModelToJSONTyped,
} from './UserListModel';
import type { ContainerState } from './ContainerState';
import {
    ContainerStateFromJSON,
    ContainerStateFromJSONTyped,
    ContainerStateToJSON,
    ContainerStateToJSONTyped,
} from './ContainerState';

/**
 * 
 * @export
 * @interface ContainerChangeCreateResponse
 */
export interface ContainerChangeCreateResponse {
    /**
     * 
     * @type {ContainerState}
     * @memberof ContainerChangeCreateResponse
     */
    newState: ContainerState;
    /**
     * 
     * @type {Date}
     * @memberof ContainerChangeCreateResponse
     */
    timestamp: Date;
    /**
     * 
     * @type {CashBoxesReadIdParameter}
     * @memberof ContainerChangeCreateResponse
     */
    containerId: CashBoxesReadIdParameter;
    /**
     * 
     * @type {UserListModel}
     * @memberof ContainerChangeCreateResponse
     */
    user: UserListModel;
}



/**
 * Check if a given object implements the ContainerChangeCreateResponse interface.
 */
export function instanceOfContainerChangeCreateResponse(value: object): value is ContainerChangeCreateResponse {
    if (!('newState' in value) || value['newState'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('containerId' in value) || value['containerId'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function ContainerChangeCreateResponseFromJSON(json: any): ContainerChangeCreateResponse {
    return ContainerChangeCreateResponseFromJSONTyped(json, false);
}

export function ContainerChangeCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerChangeCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'newState': ContainerStateFromJSON(json['newState']),
        'timestamp': (new Date(json['timestamp'])),
        'containerId': CashBoxesReadIdParameterFromJSON(json['containerId']),
        'user': UserListModelFromJSON(json['user']),
    };
}

export function ContainerChangeCreateResponseToJSON(json: any): ContainerChangeCreateResponse {
    return ContainerChangeCreateResponseToJSONTyped(json, false);
}

export function ContainerChangeCreateResponseToJSONTyped(value?: ContainerChangeCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'newState': ContainerStateToJSON(value['newState']),
        'timestamp': ((value['timestamp']).toISOString()),
        'containerId': CashBoxesReadIdParameterToJSON(value['containerId']),
        'user': UserListModelToJSON(value['user']),
    };
}

