/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMeta } from './PageMeta';
import {
    PageMetaFromJSON,
    PageMetaFromJSONTyped,
    PageMetaToJSON,
    PageMetaToJSONTyped,
} from './PageMeta';
import type { ContainerTemplateModel } from './ContainerTemplateModel';
import {
    ContainerTemplateModelFromJSON,
    ContainerTemplateModelFromJSONTyped,
    ContainerTemplateModelToJSON,
    ContainerTemplateModelToJSONTyped,
} from './ContainerTemplateModel';

/**
 * 
 * @export
 * @interface ContainerTemplateReadAllResponse
 */
export interface ContainerTemplateReadAllResponse {
    /**
     * 
     * @type {Array<ContainerTemplateModel>}
     * @memberof ContainerTemplateReadAllResponse
     */
    data: Array<ContainerTemplateModel>;
    /**
     * 
     * @type {PageMeta}
     * @memberof ContainerTemplateReadAllResponse
     */
    meta: PageMeta;
}

/**
 * Check if a given object implements the ContainerTemplateReadAllResponse interface.
 */
export function instanceOfContainerTemplateReadAllResponse(value: object): value is ContainerTemplateReadAllResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ContainerTemplateReadAllResponseFromJSON(json: any): ContainerTemplateReadAllResponse {
    return ContainerTemplateReadAllResponseFromJSONTyped(json, false);
}

export function ContainerTemplateReadAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerTemplateReadAllResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ContainerTemplateModelFromJSON)),
        'meta': PageMetaFromJSON(json['meta']),
    };
}

export function ContainerTemplateReadAllResponseToJSON(json: any): ContainerTemplateReadAllResponse {
    return ContainerTemplateReadAllResponseToJSONTyped(json, false);
}

export function ContainerTemplateReadAllResponseToJSONTyped(value?: ContainerTemplateReadAllResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ContainerTemplateModelToJSON)),
        'meta': PageMetaToJSON(value['meta']),
    };
}

