/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StoreItemListModel } from './StoreItemListModel';
import {
    StoreItemListModelFromJSON,
    StoreItemListModelFromJSONTyped,
    StoreItemListModelToJSON,
    StoreItemListModelToJSONTyped,
} from './StoreItemListModel';

/**
 * 
 * @export
 * @interface ContainerTemplateCreateResponse
 */
export interface ContainerTemplateCreateResponse {
    /**
     * 
     * @type {number}
     * @memberof ContainerTemplateCreateResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ContainerTemplateCreateResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerTemplateCreateResponse
     */
    amount: string;
    /**
     * 
     * @type {StoreItemListModel}
     * @memberof ContainerTemplateCreateResponse
     */
    storeItem: StoreItemListModel;
}

/**
 * Check if a given object implements the ContainerTemplateCreateResponse interface.
 */
export function instanceOfContainerTemplateCreateResponse(value: object): value is ContainerTemplateCreateResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('storeItem' in value) || value['storeItem'] === undefined) return false;
    return true;
}

export function ContainerTemplateCreateResponseFromJSON(json: any): ContainerTemplateCreateResponse {
    return ContainerTemplateCreateResponseFromJSONTyped(json, false);
}

export function ContainerTemplateCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerTemplateCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'amount': json['amount'],
        'storeItem': StoreItemListModelFromJSON(json['storeItem']),
    };
}

export function ContainerTemplateCreateResponseToJSON(json: any): ContainerTemplateCreateResponse {
    return ContainerTemplateCreateResponseToJSONTyped(json, false);
}

export function ContainerTemplateCreateResponseToJSONTyped(value?: ContainerTemplateCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'amount': value['amount'],
        'storeItem': StoreItemListModelToJSON(value['storeItem']),
    };
}

