/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StoreItemListModel } from './StoreItemListModel';
import {
    StoreItemListModelFromJSON,
    StoreItemListModelFromJSONTyped,
    StoreItemListModelToJSON,
    StoreItemListModelToJSONTyped,
} from './StoreItemListModel';

/**
 * 
 * @export
 * @interface ContainerTemplateUpdateResponse
 */
export interface ContainerTemplateUpdateResponse {
    /**
     * 
     * @type {number}
     * @memberof ContainerTemplateUpdateResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ContainerTemplateUpdateResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerTemplateUpdateResponse
     */
    amount: string;
    /**
     * 
     * @type {StoreItemListModel}
     * @memberof ContainerTemplateUpdateResponse
     */
    storeItem: StoreItemListModel;
}

/**
 * Check if a given object implements the ContainerTemplateUpdateResponse interface.
 */
export function instanceOfContainerTemplateUpdateResponse(value: object): value is ContainerTemplateUpdateResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('storeItem' in value) || value['storeItem'] === undefined) return false;
    return true;
}

export function ContainerTemplateUpdateResponseFromJSON(json: any): ContainerTemplateUpdateResponse {
    return ContainerTemplateUpdateResponseFromJSONTyped(json, false);
}

export function ContainerTemplateUpdateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerTemplateUpdateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'amount': json['amount'],
        'storeItem': StoreItemListModelFromJSON(json['storeItem']),
    };
}

export function ContainerTemplateUpdateResponseToJSON(json: any): ContainerTemplateUpdateResponse {
    return ContainerTemplateUpdateResponseToJSONTyped(json, false);
}

export function ContainerTemplateUpdateResponseToJSONTyped(value?: ContainerTemplateUpdateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'amount': value['amount'],
        'storeItem': StoreItemListModelToJSON(value['storeItem']),
    };
}

