/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CostCreateRequest
 */
export interface CostCreateRequest {
    /**
     * 
     * @type {number}
     * @memberof CostCreateRequest
     */
    storeItemId: number;
    /**
     * 
     * @type {string}
     * @memberof CostCreateRequest
     */
    amount: string;
    /**
     * 
     * @type {string}
     * @memberof CostCreateRequest
     */
    description: string;
}

/**
 * Check if a given object implements the CostCreateRequest interface.
 */
export function instanceOfCostCreateRequest(value: object): value is CostCreateRequest {
    if (!('storeItemId' in value) || value['storeItemId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function CostCreateRequestFromJSON(json: any): CostCreateRequest {
    return CostCreateRequestFromJSONTyped(json, false);
}

export function CostCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CostCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'storeItemId': json['storeItemId'],
        'amount': json['amount'],
        'description': json['description'],
    };
}

export function CostCreateRequestToJSON(json: any): CostCreateRequest {
    return CostCreateRequestToJSONTyped(json, false);
}

export function CostCreateRequestToJSONTyped(value?: CostCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'storeItemId': value['storeItemId'],
        'amount': value['amount'],
        'description': value['description'],
    };
}

