/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserListModel } from './UserListModel';
import {
    UserListModelFromJSON,
    UserListModelFromJSONTyped,
    UserListModelToJSON,
    UserListModelToJSONTyped,
} from './UserListModel';

/**
 * 
 * @export
 * @interface CostCreateResponse
 */
export interface CostCreateResponse {
    /**
     * 
     * @type {string}
     * @memberof CostCreateResponse
     */
    amount: string;
    /**
     * 
     * @type {Date}
     * @memberof CostCreateResponse
     */
    timestamp: Date;
    /**
     * 
     * @type {string}
     * @memberof CostCreateResponse
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof CostCreateResponse
     */
    storeItemId: number;
    /**
     * 
     * @type {UserListModel}
     * @memberof CostCreateResponse
     */
    user: UserListModel;
}

/**
 * Check if a given object implements the CostCreateResponse interface.
 */
export function instanceOfCostCreateResponse(value: object): value is CostCreateResponse {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('storeItemId' in value) || value['storeItemId'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function CostCreateResponseFromJSON(json: any): CostCreateResponse {
    return CostCreateResponseFromJSONTyped(json, false);
}

export function CostCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CostCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'timestamp': (new Date(json['timestamp'])),
        'description': json['description'],
        'storeItemId': json['storeItemId'],
        'user': UserListModelFromJSON(json['user']),
    };
}

export function CostCreateResponseToJSON(json: any): CostCreateResponse {
    return CostCreateResponseToJSONTyped(json, false);
}

export function CostCreateResponseToJSONTyped(value?: CostCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'timestamp': value['timestamp'].toISOString(),
        'description': value['description'],
        'storeItemId': value['storeItemId'],
        'user': UserListModelToJSON(value['user']),
    };
}

