/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LayoutListModel } from './LayoutListModel';
import {
    LayoutListModelFromJSON,
    LayoutListModelFromJSONTyped,
    LayoutListModelToJSON,
    LayoutListModelToJSONTyped,
} from './LayoutListModel';

/**
 * 
 * @export
 * @interface LayoutItemModelLayoutLinkModel
 */
export interface LayoutItemModelLayoutLinkModel {
    /**
     * 
     * @type {string}
     * @memberof LayoutItemModelLayoutLinkModel
     */
    type: LayoutItemModelLayoutLinkModelTypeEnum;
    /**
     * 
     * @type {LayoutListModel}
     * @memberof LayoutItemModelLayoutLinkModel
     */
    target: LayoutListModel;
    /**
     * 
     * @type {number}
     * @memberof LayoutItemModelLayoutLinkModel
     */
    x: number;
    /**
     * 
     * @type {number}
     * @memberof LayoutItemModelLayoutLinkModel
     */
    y: number;
}


/**
 * @export
 */
export const LayoutItemModelLayoutLinkModelTypeEnum = {
    Layout: 'Layout'
} as const;
export type LayoutItemModelLayoutLinkModelTypeEnum = typeof LayoutItemModelLayoutLinkModelTypeEnum[keyof typeof LayoutItemModelLayoutLinkModelTypeEnum];


/**
 * Check if a given object implements the LayoutItemModelLayoutLinkModel interface.
 */
export function instanceOfLayoutItemModelLayoutLinkModel(value: object): value is LayoutItemModelLayoutLinkModel {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('target' in value) || value['target'] === undefined) return false;
    if (!('x' in value) || value['x'] === undefined) return false;
    if (!('y' in value) || value['y'] === undefined) return false;
    return true;
}

export function LayoutItemModelLayoutLinkModelFromJSON(json: any): LayoutItemModelLayoutLinkModel {
    return LayoutItemModelLayoutLinkModelFromJSONTyped(json, false);
}

export function LayoutItemModelLayoutLinkModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): LayoutItemModelLayoutLinkModel {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'target': LayoutListModelFromJSON(json['target']),
        'x': json['x'],
        'y': json['y'],
    };
}

export function LayoutItemModelLayoutLinkModelToJSON(json: any): LayoutItemModelLayoutLinkModel {
    return LayoutItemModelLayoutLinkModelToJSONTyped(json, false);
}

export function LayoutItemModelLayoutLinkModelToJSONTyped(value?: LayoutItemModelLayoutLinkModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'target': LayoutListModelToJSON(value['target']),
        'x': value['x'],
        'y': value['y'],
    };
}

