/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CashBoxesReadIdParameter } from './CashBoxesReadIdParameter';
import {
    CashBoxesReadIdParameterFromJSON,
    CashBoxesReadIdParameterFromJSONTyped,
    CashBoxesReadIdParameterToJSON,
    CashBoxesReadIdParameterToJSONTyped,
} from './CashBoxesReadIdParameter';
import type { PipeListModel } from './PipeListModel';
import {
    PipeListModelFromJSON,
    PipeListModelFromJSONTyped,
    PipeListModelToJSON,
    PipeListModelToJSONTyped,
} from './PipeListModel';

/**
 * 
 * @export
 * @interface LayoutItemModelLayoutPipeModel
 */
export interface LayoutItemModelLayoutPipeModel {
    /**
     * 
     * @type {string}
     * @memberof LayoutItemModelLayoutPipeModel
     */
    type?: LayoutItemModelLayoutPipeModelTypeEnum;
    /**
     * 
     * @type {PipeListModel}
     * @memberof LayoutItemModelLayoutPipeModel
     */
    target: PipeListModel;
    /**
     * 
     * @type {CashBoxesReadIdParameter}
     * @memberof LayoutItemModelLayoutPipeModel
     */
    x: CashBoxesReadIdParameter;
    /**
     * 
     * @type {CashBoxesReadIdParameter}
     * @memberof LayoutItemModelLayoutPipeModel
     */
    y: CashBoxesReadIdParameter;
}


/**
 * @export
 */
export const LayoutItemModelLayoutPipeModelTypeEnum = {
    Pipe: 'Pipe'
} as const;
export type LayoutItemModelLayoutPipeModelTypeEnum = typeof LayoutItemModelLayoutPipeModelTypeEnum[keyof typeof LayoutItemModelLayoutPipeModelTypeEnum];


/**
 * Check if a given object implements the LayoutItemModelLayoutPipeModel interface.
 */
export function instanceOfLayoutItemModelLayoutPipeModel(value: object): value is LayoutItemModelLayoutPipeModel {
    if (!('target' in value) || value['target'] === undefined) return false;
    if (!('x' in value) || value['x'] === undefined) return false;
    if (!('y' in value) || value['y'] === undefined) return false;
    return true;
}

export function LayoutItemModelLayoutPipeModelFromJSON(json: any): LayoutItemModelLayoutPipeModel {
    return LayoutItemModelLayoutPipeModelFromJSONTyped(json, false);
}

export function LayoutItemModelLayoutPipeModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): LayoutItemModelLayoutPipeModel {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'target': PipeListModelFromJSON(json['target']),
        'x': CashBoxesReadIdParameterFromJSON(json['x']),
        'y': CashBoxesReadIdParameterFromJSON(json['y']),
    };
}

export function LayoutItemModelLayoutPipeModelToJSON(json: any): LayoutItemModelLayoutPipeModel {
    return LayoutItemModelLayoutPipeModelToJSONTyped(json, false);
}

export function LayoutItemModelLayoutPipeModelToJSONTyped(value?: LayoutItemModelLayoutPipeModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'target': PipeListModelToJSON(value['target']),
        'x': CashBoxesReadIdParameterToJSON(value['x']),
        'y': CashBoxesReadIdParameterToJSON(value['y']),
    };
}

