/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LayoutItemModel } from './LayoutItemModel';
import {
    LayoutItemModelFromJSON,
    LayoutItemModelFromJSONTyped,
    LayoutItemModelToJSON,
    LayoutItemModelToJSONTyped,
} from './LayoutItemModel';

/**
 * 
 * @export
 * @interface LayoutCreateResponse
 */
export interface LayoutCreateResponse {
    /**
     * 
     * @type {number}
     * @memberof LayoutCreateResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof LayoutCreateResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof LayoutCreateResponse
     */
    image: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof LayoutCreateResponse
     */
    topLevel: boolean;
    /**
     * 
     * @type {Array<LayoutItemModel>}
     * @memberof LayoutCreateResponse
     */
    layoutItems: Array<LayoutItemModel>;
}

/**
 * Check if a given object implements the LayoutCreateResponse interface.
 */
export function instanceOfLayoutCreateResponse(value: object): value is LayoutCreateResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('topLevel' in value) || value['topLevel'] === undefined) return false;
    if (!('layoutItems' in value) || value['layoutItems'] === undefined) return false;
    return true;
}

export function LayoutCreateResponseFromJSON(json: any): LayoutCreateResponse {
    return LayoutCreateResponseFromJSONTyped(json, false);
}

export function LayoutCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LayoutCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'image': json['image'],
        'topLevel': json['topLevel'],
        'layoutItems': ((json['layoutItems'] as Array<any>).map(LayoutItemModelFromJSON)),
    };
}

export function LayoutCreateResponseToJSON(json: any): LayoutCreateResponse {
    return LayoutCreateResponseToJSONTyped(json, false);
}

export function LayoutCreateResponseToJSONTyped(value?: LayoutCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'image': value['image'],
        'topLevel': value['topLevel'],
        'layoutItems': ((value['layoutItems'] as Array<any>).map(LayoutItemModelToJSON)),
    };
}

