/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CashBoxesReadIdParameter } from './CashBoxesReadIdParameter';
import {
    CashBoxesReadIdParameterFromJSON,
    CashBoxesReadIdParameterFromJSONTyped,
    CashBoxesReadIdParameterToJSON,
    CashBoxesReadIdParameterToJSONTyped,
} from './CashBoxesReadIdParameter';
import type { LayoutItemType } from './LayoutItemType';
import {
    LayoutItemTypeFromJSON,
    LayoutItemTypeFromJSONTyped,
    LayoutItemTypeToJSON,
    LayoutItemTypeToJSONTyped,
} from './LayoutItemType';

/**
 * 
 * @export
 * @interface LayoutItemCreateRequest
 */
export interface LayoutItemCreateRequest {
    /**
     * 
     * @type {CashBoxesReadIdParameter}
     * @memberof LayoutItemCreateRequest
     */
    x: CashBoxesReadIdParameter;
    /**
     * 
     * @type {CashBoxesReadIdParameter}
     * @memberof LayoutItemCreateRequest
     */
    y: CashBoxesReadIdParameter;
    /**
     * 
     * @type {CashBoxesReadIdParameter}
     * @memberof LayoutItemCreateRequest
     */
    targetId: CashBoxesReadIdParameter;
    /**
     * 
     * @type {LayoutItemType}
     * @memberof LayoutItemCreateRequest
     */
    type: LayoutItemType;
}



/**
 * Check if a given object implements the LayoutItemCreateRequest interface.
 */
export function instanceOfLayoutItemCreateRequest(value: object): value is LayoutItemCreateRequest {
    if (!('x' in value) || value['x'] === undefined) return false;
    if (!('y' in value) || value['y'] === undefined) return false;
    if (!('targetId' in value) || value['targetId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function LayoutItemCreateRequestFromJSON(json: any): LayoutItemCreateRequest {
    return LayoutItemCreateRequestFromJSONTyped(json, false);
}

export function LayoutItemCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LayoutItemCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'x': CashBoxesReadIdParameterFromJSON(json['x']),
        'y': CashBoxesReadIdParameterFromJSON(json['y']),
        'targetId': CashBoxesReadIdParameterFromJSON(json['targetId']),
        'type': LayoutItemTypeFromJSON(json['type']),
    };
}

export function LayoutItemCreateRequestToJSON(json: any): LayoutItemCreateRequest {
    return LayoutItemCreateRequestToJSONTyped(json, false);
}

export function LayoutItemCreateRequestToJSONTyped(value?: LayoutItemCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'x': CashBoxesReadIdParameterToJSON(value['x']),
        'y': CashBoxesReadIdParameterToJSON(value['y']),
        'targetId': CashBoxesReadIdParameterToJSON(value['targetId']),
        'type': LayoutItemTypeToJSON(value['type']),
    };
}

