/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModifierListModel } from './ModifierListModel';
import {
    ModifierListModelFromJSON,
    ModifierListModelFromJSONTyped,
    ModifierListModelToJSON,
    ModifierListModelToJSONTyped,
} from './ModifierListModel';
import type { PageMeta } from './PageMeta';
import {
    PageMetaFromJSON,
    PageMetaFromJSONTyped,
    PageMetaToJSON,
    PageMetaToJSONTyped,
} from './PageMeta';

/**
 * 
 * @export
 * @interface ModifierReadAllResponse
 */
export interface ModifierReadAllResponse {
    /**
     * 
     * @type {Array<ModifierListModel>}
     * @memberof ModifierReadAllResponse
     */
    data: Array<ModifierListModel>;
    /**
     * 
     * @type {PageMeta}
     * @memberof ModifierReadAllResponse
     */
    meta: PageMeta;
}

/**
 * Check if a given object implements the ModifierReadAllResponse interface.
 */
export function instanceOfModifierReadAllResponse(value: object): value is ModifierReadAllResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ModifierReadAllResponseFromJSON(json: any): ModifierReadAllResponse {
    return ModifierReadAllResponseFromJSONTyped(json, false);
}

export function ModifierReadAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModifierReadAllResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ModifierListModelFromJSON)),
        'meta': PageMetaFromJSON(json['meta']),
    };
}

export function ModifierReadAllResponseToJSON(json: any): ModifierReadAllResponse {
    return ModifierReadAllResponseToJSONTyped(json, false);
}

export function ModifierReadAllResponseToJSONTyped(value?: ModifierReadAllResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ModifierListModelToJSON)),
        'meta': PageMetaToJSON(value['meta']),
    };
}

