/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CashBoxesReadIdParameter } from './CashBoxesReadIdParameter';
import {
    CashBoxesReadIdParameterFromJSON,
    CashBoxesReadIdParameterFromJSONTyped,
    CashBoxesReadIdParameterToJSON,
    CashBoxesReadIdParameterToJSONTyped,
} from './CashBoxesReadIdParameter';

/**
 * 
 * @export
 * @interface ModificationCreateRequest
 */
export interface ModificationCreateRequest {
    /**
     * 
     * @type {CashBoxesReadIdParameter}
     * @memberof ModificationCreateRequest
     */
    amount: CashBoxesReadIdParameter;
    /**
     * 
     * @type {CashBoxesReadIdParameter}
     * @memberof ModificationCreateRequest
     */
    modifierId: CashBoxesReadIdParameter;
}

/**
 * Check if a given object implements the ModificationCreateRequest interface.
 */
export function instanceOfModificationCreateRequest(value: object): value is ModificationCreateRequest {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('modifierId' in value) || value['modifierId'] === undefined) return false;
    return true;
}

export function ModificationCreateRequestFromJSON(json: any): ModificationCreateRequest {
    return ModificationCreateRequestFromJSONTyped(json, false);
}

export function ModificationCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModificationCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': CashBoxesReadIdParameterFromJSON(json['amount']),
        'modifierId': CashBoxesReadIdParameterFromJSON(json['modifierId']),
    };
}

export function ModificationCreateRequestToJSON(json: any): ModificationCreateRequest {
    return ModificationCreateRequestToJSONTyped(json, false);
}

export function ModificationCreateRequestToJSONTyped(value?: ModificationCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': CashBoxesReadIdParameterToJSON(value['amount']),
        'modifierId': CashBoxesReadIdParameterToJSON(value['modifierId']),
    };
}

