/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CashBoxesReadIdParameter } from './CashBoxesReadIdParameter';
import {
    CashBoxesReadIdParameterFromJSON,
    CashBoxesReadIdParameterFromJSONTyped,
    CashBoxesReadIdParameterToJSON,
    CashBoxesReadIdParameterToJSONTyped,
} from './CashBoxesReadIdParameter';
import type { AccountTransactionModelAmount } from './AccountTransactionModelAmount';
import {
    AccountTransactionModelAmountFromJSON,
    AccountTransactionModelAmountFromJSONTyped,
    AccountTransactionModelAmountToJSON,
    AccountTransactionModelAmountToJSONTyped,
} from './AccountTransactionModelAmount';

/**
 * 
 * @export
 * @interface ModifierListModel
 */
export interface ModifierListModel {
    /**
     * 
     * @type {CashBoxesReadIdParameter}
     * @memberof ModifierListModel
     */
    id: CashBoxesReadIdParameter;
    /**
     * 
     * @type {string}
     * @memberof ModifierListModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ModifierListModel
     */
    image: string | null;
    /**
     * 
     * @type {AccountTransactionModelAmount}
     * @memberof ModifierListModel
     */
    marginPercent: AccountTransactionModelAmount;
    /**
     * 
     * @type {AccountTransactionModelAmount}
     * @memberof ModifierListModel
     */
    marginStatic: AccountTransactionModelAmount;
    /**
     * 
     * @type {AccountTransactionModelAmount}
     * @memberof ModifierListModel
     */
    prestigeAmount: AccountTransactionModelAmount;
}

/**
 * Check if a given object implements the ModifierListModel interface.
 */
export function instanceOfModifierListModel(value: object): value is ModifierListModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('marginPercent' in value) || value['marginPercent'] === undefined) return false;
    if (!('marginStatic' in value) || value['marginStatic'] === undefined) return false;
    if (!('prestigeAmount' in value) || value['prestigeAmount'] === undefined) return false;
    return true;
}

export function ModifierListModelFromJSON(json: any): ModifierListModel {
    return ModifierListModelFromJSONTyped(json, false);
}

export function ModifierListModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModifierListModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': CashBoxesReadIdParameterFromJSON(json['id']),
        'name': json['name'],
        'image': json['image'],
        'marginPercent': AccountTransactionModelAmountFromJSON(json['marginPercent']),
        'marginStatic': AccountTransactionModelAmountFromJSON(json['marginStatic']),
        'prestigeAmount': AccountTransactionModelAmountFromJSON(json['prestigeAmount']),
    };
}

export function ModifierListModelToJSON(json: any): ModifierListModel {
    return ModifierListModelToJSONTyped(json, false);
}

export function ModifierListModelToJSONTyped(value?: ModifierListModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': CashBoxesReadIdParameterToJSON(value['id']),
        'name': value['name'],
        'image': value['image'],
        'marginPercent': AccountTransactionModelAmountToJSON(value['marginPercent']),
        'marginStatic': AccountTransactionModelAmountToJSON(value['marginStatic']),
        'prestigeAmount': AccountTransactionModelAmountToJSON(value['prestigeAmount']),
    };
}

