/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CashBoxesReadIdParameter } from './CashBoxesReadIdParameter';
import {
    CashBoxesReadIdParameterFromJSON,
    CashBoxesReadIdParameterFromJSONTyped,
    CashBoxesReadIdParameterToJSON,
    CashBoxesReadIdParameterToJSONTyped,
} from './CashBoxesReadIdParameter';
import type { AccountTransactionModelAmount } from './AccountTransactionModelAmount';
import {
    AccountTransactionModelAmountFromJSON,
    AccountTransactionModelAmountFromJSONTyped,
    AccountTransactionModelAmountToJSON,
    AccountTransactionModelAmountToJSONTyped,
} from './AccountTransactionModelAmount';

/**
 * 
 * @export
 * @interface ModificationModel
 */
export interface ModificationModel {
    /**
     * 
     * @type {CashBoxesReadIdParameter}
     * @memberof ModificationModel
     */
    amount: CashBoxesReadIdParameter;
    /**
     * 
     * @type {string}
     * @memberof ModificationModel
     */
    modifierName: string;
    /**
     * 
     * @type {AccountTransactionModelAmount}
     * @memberof ModificationModel
     */
    priceChange: AccountTransactionModelAmount;
}

/**
 * Check if a given object implements the ModificationModel interface.
 */
export function instanceOfModificationModel(value: object): value is ModificationModel {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('modifierName' in value) || value['modifierName'] === undefined) return false;
    if (!('priceChange' in value) || value['priceChange'] === undefined) return false;
    return true;
}

export function ModificationModelFromJSON(json: any): ModificationModel {
    return ModificationModelFromJSONTyped(json, false);
}

export function ModificationModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModificationModel {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': CashBoxesReadIdParameterFromJSON(json['amount']),
        'modifierName': json['modifierName'],
        'priceChange': AccountTransactionModelAmountFromJSON(json['priceChange']),
    };
}

export function ModificationModelToJSON(json: any): ModificationModel {
    return ModificationModelToJSONTyped(json, false);
}

export function ModificationModelToJSONTyped(value?: ModificationModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': CashBoxesReadIdParameterToJSON(value['amount']),
        'modifierName': value['modifierName'],
        'priceChange': AccountTransactionModelAmountToJSON(value['priceChange']),
    };
}

