/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModifierCreateRequestMarginPercent } from './ModifierCreateRequestMarginPercent';
import {
    ModifierCreateRequestMarginPercentFromJSON,
    ModifierCreateRequestMarginPercentFromJSONTyped,
    ModifierCreateRequestMarginPercentToJSON,
    ModifierCreateRequestMarginPercentToJSONTyped,
} from './ModifierCreateRequestMarginPercent';
import type { CashBoxesReadIdParameter } from './CashBoxesReadIdParameter';
import {
    CashBoxesReadIdParameterFromJSON,
    CashBoxesReadIdParameterFromJSONTyped,
    CashBoxesReadIdParameterToJSON,
    CashBoxesReadIdParameterToJSONTyped,
} from './CashBoxesReadIdParameter';
import type { ModifierCreateRequestMarginStatic } from './ModifierCreateRequestMarginStatic';
import {
    ModifierCreateRequestMarginStaticFromJSON,
    ModifierCreateRequestMarginStaticFromJSONTyped,
    ModifierCreateRequestMarginStaticToJSON,
    ModifierCreateRequestMarginStaticToJSONTyped,
} from './ModifierCreateRequestMarginStatic';

/**
 * 
 * @export
 * @interface ModifierCreateRequest
 */
export interface ModifierCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof ModifierCreateRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ModifierCreateRequest
     */
    image: string | null;
    /**
     * 
     * @type {ModifierCreateRequestMarginPercent}
     * @memberof ModifierCreateRequest
     */
    marginPercent: ModifierCreateRequestMarginPercent;
    /**
     * 
     * @type {ModifierCreateRequestMarginStatic}
     * @memberof ModifierCreateRequest
     */
    marginStatic: ModifierCreateRequestMarginStatic;
    /**
     * 
     * @type {ModifierCreateRequestMarginStatic}
     * @memberof ModifierCreateRequest
     */
    prestigeAmount: ModifierCreateRequestMarginStatic;
    /**
     * 
     * @type {Array<CashBoxesReadIdParameter>}
     * @memberof ModifierCreateRequest
     */
    categoryIds: Array<CashBoxesReadIdParameter>;
    /**
     * 
     * @type {Array<CashBoxesReadIdParameter>}
     * @memberof ModifierCreateRequest
     */
    targetIds: Array<CashBoxesReadIdParameter>;
}

/**
 * Check if a given object implements the ModifierCreateRequest interface.
 */
export function instanceOfModifierCreateRequest(value: object): value is ModifierCreateRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('marginPercent' in value) || value['marginPercent'] === undefined) return false;
    if (!('marginStatic' in value) || value['marginStatic'] === undefined) return false;
    if (!('prestigeAmount' in value) || value['prestigeAmount'] === undefined) return false;
    if (!('categoryIds' in value) || value['categoryIds'] === undefined) return false;
    if (!('targetIds' in value) || value['targetIds'] === undefined) return false;
    return true;
}

export function ModifierCreateRequestFromJSON(json: any): ModifierCreateRequest {
    return ModifierCreateRequestFromJSONTyped(json, false);
}

export function ModifierCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModifierCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'image': json['image'],
        'marginPercent': ModifierCreateRequestMarginPercentFromJSON(json['marginPercent']),
        'marginStatic': ModifierCreateRequestMarginStaticFromJSON(json['marginStatic']),
        'prestigeAmount': ModifierCreateRequestMarginStaticFromJSON(json['prestigeAmount']),
        'categoryIds': ((json['categoryIds'] as Array<any>).map(CashBoxesReadIdParameterFromJSON)),
        'targetIds': ((json['targetIds'] as Array<any>).map(CashBoxesReadIdParameterFromJSON)),
    };
}

export function ModifierCreateRequestToJSON(json: any): ModifierCreateRequest {
    return ModifierCreateRequestToJSONTyped(json, false);
}

export function ModifierCreateRequestToJSONTyped(value?: ModifierCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'image': value['image'],
        'marginPercent': ModifierCreateRequestMarginPercentToJSON(value['marginPercent']),
        'marginStatic': ModifierCreateRequestMarginStaticToJSON(value['marginStatic']),
        'prestigeAmount': ModifierCreateRequestMarginStaticToJSON(value['prestigeAmount']),
        'categoryIds': ((value['categoryIds'] as Array<any>).map(CashBoxesReadIdParameterToJSON)),
        'targetIds': ((value['targetIds'] as Array<any>).map(CashBoxesReadIdParameterToJSON)),
    };
}

