/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SaleItemListModel } from './SaleItemListModel';
import {
    SaleItemListModelFromJSON,
    SaleItemListModelFromJSONTyped,
    SaleItemListModelToJSON,
    SaleItemListModelToJSONTyped,
} from './SaleItemListModel';
import type { CategoryModel } from './CategoryModel';
import {
    CategoryModelFromJSON,
    CategoryModelFromJSONTyped,
    CategoryModelToJSON,
    CategoryModelToJSONTyped,
} from './CategoryModel';

/**
 * 
 * @export
 * @interface ModifierReadResponse
 */
export interface ModifierReadResponse {
    /**
     * 
     * @type {number}
     * @memberof ModifierReadResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ModifierReadResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ModifierReadResponse
     */
    image: string | null;
    /**
     * 
     * @type {string}
     * @memberof ModifierReadResponse
     */
    marginPercent: string;
    /**
     * 
     * @type {string}
     * @memberof ModifierReadResponse
     */
    marginStatic: string;
    /**
     * 
     * @type {string}
     * @memberof ModifierReadResponse
     */
    prestigeAmount: string;
    /**
     * 
     * @type {Array<CategoryModel>}
     * @memberof ModifierReadResponse
     */
    categories: Array<CategoryModel>;
    /**
     * 
     * @type {Array<SaleItemListModel>}
     * @memberof ModifierReadResponse
     */
    targets: Array<SaleItemListModel>;
}

/**
 * Check if a given object implements the ModifierReadResponse interface.
 */
export function instanceOfModifierReadResponse(value: object): value is ModifierReadResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('marginPercent' in value) || value['marginPercent'] === undefined) return false;
    if (!('marginStatic' in value) || value['marginStatic'] === undefined) return false;
    if (!('prestigeAmount' in value) || value['prestigeAmount'] === undefined) return false;
    if (!('categories' in value) || value['categories'] === undefined) return false;
    if (!('targets' in value) || value['targets'] === undefined) return false;
    return true;
}

export function ModifierReadResponseFromJSON(json: any): ModifierReadResponse {
    return ModifierReadResponseFromJSONTyped(json, false);
}

export function ModifierReadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModifierReadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'image': json['image'],
        'marginPercent': json['marginPercent'],
        'marginStatic': json['marginStatic'],
        'prestigeAmount': json['prestigeAmount'],
        'categories': ((json['categories'] as Array<any>).map(CategoryModelFromJSON)),
        'targets': ((json['targets'] as Array<any>).map(SaleItemListModelFromJSON)),
    };
}

export function ModifierReadResponseToJSON(json: any): ModifierReadResponse {
    return ModifierReadResponseToJSONTyped(json, false);
}

export function ModifierReadResponseToJSONTyped(value?: ModifierReadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'image': value['image'],
        'marginPercent': value['marginPercent'],
        'marginStatic': value['marginStatic'],
        'prestigeAmount': value['prestigeAmount'],
        'categories': ((value['categories'] as Array<any>).map(CategoryModelToJSON)),
        'targets': ((value['targets'] as Array<any>).map(SaleItemListModelToJSON)),
    };
}

