/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CashBoxesReadIdParameter } from './CashBoxesReadIdParameter';
import {
    CashBoxesReadIdParameterFromJSON,
    CashBoxesReadIdParameterFromJSONTyped,
    CashBoxesReadIdParameterToJSON,
    CashBoxesReadIdParameterToJSONTyped,
} from './CashBoxesReadIdParameter';

/**
 * 
 * @export
 * @interface PageMeta
 */
export interface PageMeta {
    /**
     * 
     * @type {CashBoxesReadIdParameter}
     * @memberof PageMeta
     */
    page: CashBoxesReadIdParameter;
    /**
     * 
     * @type {CashBoxesReadIdParameter}
     * @memberof PageMeta
     */
    pageSize: CashBoxesReadIdParameter;
    /**
     * 
     * @type {CashBoxesReadIdParameter}
     * @memberof PageMeta
     */
    total: CashBoxesReadIdParameter;
}

/**
 * Check if a given object implements the PageMeta interface.
 */
export function instanceOfPageMeta(value: object): value is PageMeta {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function PageMetaFromJSON(json: any): PageMeta {
    return PageMetaFromJSONTyped(json, false);
}

export function PageMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'page': CashBoxesReadIdParameterFromJSON(json['page']),
        'pageSize': CashBoxesReadIdParameterFromJSON(json['pageSize']),
        'total': CashBoxesReadIdParameterFromJSON(json['total']),
    };
}

export function PageMetaToJSON(json: any): PageMeta {
    return PageMetaToJSONTyped(json, false);
}

export function PageMetaToJSONTyped(value?: PageMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': CashBoxesReadIdParameterToJSON(value['page']),
        'pageSize': CashBoxesReadIdParameterToJSON(value['pageSize']),
        'total': CashBoxesReadIdParameterToJSON(value['total']),
    };
}

