/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PipeUpdateModel
 */
export interface PipeUpdateModel {
    /**
     * 
     * @type {string}
     * @memberof PipeUpdateModel
     */
    name: string;
}

/**
 * Check if a given object implements the PipeUpdateModel interface.
 */
export function instanceOfPipeUpdateModel(value: object): value is PipeUpdateModel {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function PipeUpdateModelFromJSON(json: any): PipeUpdateModel {
    return PipeUpdateModelFromJSONTyped(json, false);
}

export function PipeUpdateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PipeUpdateModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function PipeUpdateModelToJSON(json: any): PipeUpdateModel {
    return PipeUpdateModelToJSONTyped(json, false);
}

export function PipeUpdateModelToJSONTyped(value?: PipeUpdateModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

