/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PipeCreateResponse
 */
export interface PipeCreateResponse {
    /**
     * 
     * @type {number}
     * @memberof PipeCreateResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PipeCreateResponse
     */
    name: string;
}

/**
 * Check if a given object implements the PipeCreateResponse interface.
 */
export function instanceOfPipeCreateResponse(value: object): value is PipeCreateResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function PipeCreateResponseFromJSON(json: any): PipeCreateResponse {
    return PipeCreateResponseFromJSONTyped(json, false);
}

export function PipeCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PipeCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function PipeCreateResponseToJSON(json: any): PipeCreateResponse {
    return PipeCreateResponseToJSONTyped(json, false);
}

export function PipeCreateResponseToJSONTyped(value?: PipeCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

