/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContainerPipeModel } from './ContainerPipeModel';
import {
    ContainerPipeModelFromJSON,
    ContainerPipeModelFromJSONTyped,
    ContainerPipeModelToJSON,
    ContainerPipeModelToJSONTyped,
} from './ContainerPipeModel';
import type { CashBoxesReadIdParameter } from './CashBoxesReadIdParameter';
import {
    CashBoxesReadIdParameterFromJSON,
    CashBoxesReadIdParameterFromJSONTyped,
    CashBoxesReadIdParameterToJSON,
    CashBoxesReadIdParameterToJSONTyped,
} from './CashBoxesReadIdParameter';

/**
 * 
 * @export
 * @interface PipeReadResponse
 */
export interface PipeReadResponse {
    /**
     * 
     * @type {CashBoxesReadIdParameter}
     * @memberof PipeReadResponse
     */
    id: CashBoxesReadIdParameter;
    /**
     * 
     * @type {string}
     * @memberof PipeReadResponse
     */
    name: string;
    /**
     * 
     * @type {Array<ContainerPipeModel>}
     * @memberof PipeReadResponse
     */
    containers: Array<ContainerPipeModel>;
}

/**
 * Check if a given object implements the PipeReadResponse interface.
 */
export function instanceOfPipeReadResponse(value: object): value is PipeReadResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('containers' in value) || value['containers'] === undefined) return false;
    return true;
}

export function PipeReadResponseFromJSON(json: any): PipeReadResponse {
    return PipeReadResponseFromJSONTyped(json, false);
}

export function PipeReadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PipeReadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': CashBoxesReadIdParameterFromJSON(json['id']),
        'name': json['name'],
        'containers': ((json['containers'] as Array<any>).map(ContainerPipeModelFromJSON)),
    };
}

export function PipeReadResponseToJSON(json: any): PipeReadResponse {
    return PipeReadResponseToJSONTyped(json, false);
}

export function PipeReadResponseToJSONTyped(value?: PipeReadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': CashBoxesReadIdParameterToJSON(value['id']),
        'name': value['name'],
        'containers': ((value['containers'] as Array<any>).map(ContainerPipeModelToJSON)),
    };
}

