/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CashBoxesReadIdParameter } from './CashBoxesReadIdParameter';
import {
    CashBoxesReadIdParameterFromJSON,
    CashBoxesReadIdParameterFromJSONTyped,
    CashBoxesReadIdParameterToJSON,
    CashBoxesReadIdParameterToJSONTyped,
} from './CashBoxesReadIdParameter';
import type { SaleTransactionItemCreateRequest } from './SaleTransactionItemCreateRequest';
import {
    SaleTransactionItemCreateRequestFromJSON,
    SaleTransactionItemCreateRequestFromJSONTyped,
    SaleTransactionItemCreateRequestToJSON,
    SaleTransactionItemCreateRequestToJSONTyped,
} from './SaleTransactionItemCreateRequest';

/**
 * 
 * @export
 * @interface SaleTransactionUpdateRequestModel
 */
export interface SaleTransactionUpdateRequestModel {
    /**
     * 
     * @type {string}
     * @memberof SaleTransactionUpdateRequestModel
     */
    note?: string | null;
    /**
     * 
     * @type {CashBoxesReadIdParameter}
     * @memberof SaleTransactionUpdateRequestModel
     */
    storeId: CashBoxesReadIdParameter;
    /**
     * 
     * @type {Array<SaleTransactionItemCreateRequest>}
     * @memberof SaleTransactionUpdateRequestModel
     */
    saleTransactionItems?: Array<SaleTransactionItemCreateRequest>;
}

/**
 * Check if a given object implements the SaleTransactionUpdateRequestModel interface.
 */
export function instanceOfSaleTransactionUpdateRequestModel(value: object): value is SaleTransactionUpdateRequestModel {
    if (!('storeId' in value) || value['storeId'] === undefined) return false;
    return true;
}

export function SaleTransactionUpdateRequestModelFromJSON(json: any): SaleTransactionUpdateRequestModel {
    return SaleTransactionUpdateRequestModelFromJSONTyped(json, false);
}

export function SaleTransactionUpdateRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaleTransactionUpdateRequestModel {
    if (json == null) {
        return json;
    }
    return {
        
        'note': json['note'] == null ? undefined : json['note'],
        'storeId': CashBoxesReadIdParameterFromJSON(json['storeId']),
        'saleTransactionItems': json['saleTransactionItems'] == null ? undefined : ((json['saleTransactionItems'] as Array<any>).map(SaleTransactionItemCreateRequestFromJSON)),
    };
}

export function SaleTransactionUpdateRequestModelToJSON(json: any): SaleTransactionUpdateRequestModel {
    return SaleTransactionUpdateRequestModelToJSONTyped(json, false);
}

export function SaleTransactionUpdateRequestModelToJSONTyped(value?: SaleTransactionUpdateRequestModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'note': value['note'],
        'storeId': CashBoxesReadIdParameterToJSON(value['storeId']),
        'saleTransactionItems': value['saleTransactionItems'] == null ? undefined : ((value['saleTransactionItems'] as Array<any>).map(SaleTransactionItemCreateRequestToJSON)),
    };
}

