/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PrintType } from './PrintType';
import {
    PrintTypeFromJSON,
    PrintTypeFromJSONTyped,
    PrintTypeToJSON,
    PrintTypeToJSONTyped,
} from './PrintType';
import type { ModifierCreateRequestMarginPercent } from './ModifierCreateRequestMarginPercent';
import {
    ModifierCreateRequestMarginPercentFromJSON,
    ModifierCreateRequestMarginPercentFromJSONTyped,
    ModifierCreateRequestMarginPercentToJSON,
    ModifierCreateRequestMarginPercentToJSONTyped,
} from './ModifierCreateRequestMarginPercent';
import type { CashBoxesReadIdParameter } from './CashBoxesReadIdParameter';
import {
    CashBoxesReadIdParameterFromJSON,
    CashBoxesReadIdParameterFromJSONTyped,
    CashBoxesReadIdParameterToJSON,
    CashBoxesReadIdParameterToJSONTyped,
} from './CashBoxesReadIdParameter';
import type { ModifierCreateRequestMarginStatic } from './ModifierCreateRequestMarginStatic';
import {
    ModifierCreateRequestMarginStaticFromJSON,
    ModifierCreateRequestMarginStaticFromJSONTyped,
    ModifierCreateRequestMarginStaticToJSON,
    ModifierCreateRequestMarginStaticToJSONTyped,
} from './ModifierCreateRequestMarginStatic';

/**
 * 
 * @export
 * @interface SaleItemUpdateModel
 */
export interface SaleItemUpdateModel {
    /**
     * 
     * @type {string}
     * @memberof SaleItemUpdateModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SaleItemUpdateModel
     */
    image?: string | null;
    /**
     * 
     * @type {ModifierCreateRequestMarginPercent}
     * @memberof SaleItemUpdateModel
     */
    marginPercent?: ModifierCreateRequestMarginPercent;
    /**
     * 
     * @type {ModifierCreateRequestMarginStatic}
     * @memberof SaleItemUpdateModel
     */
    marginStatic?: ModifierCreateRequestMarginStatic;
    /**
     * 
     * @type {ModifierCreateRequestMarginStatic}
     * @memberof SaleItemUpdateModel
     */
    prestigeAmount?: ModifierCreateRequestMarginStatic;
    /**
     * 
     * @type {PrintType}
     * @memberof SaleItemUpdateModel
     */
    printType?: PrintType;
    /**
     * 
     * @type {Array<CashBoxesReadIdParameter>}
     * @memberof SaleItemUpdateModel
     */
    categoryIds?: Array<CashBoxesReadIdParameter>;
    /**
     * 
     * @type {Array<CashBoxesReadIdParameter>}
     * @memberof SaleItemUpdateModel
     */
    modifierIds?: Array<CashBoxesReadIdParameter>;
}



/**
 * Check if a given object implements the SaleItemUpdateModel interface.
 */
export function instanceOfSaleItemUpdateModel(value: object): value is SaleItemUpdateModel {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function SaleItemUpdateModelFromJSON(json: any): SaleItemUpdateModel {
    return SaleItemUpdateModelFromJSONTyped(json, false);
}

export function SaleItemUpdateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaleItemUpdateModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'image': json['image'] == null ? undefined : json['image'],
        'marginPercent': json['marginPercent'] == null ? undefined : ModifierCreateRequestMarginPercentFromJSON(json['marginPercent']),
        'marginStatic': json['marginStatic'] == null ? undefined : ModifierCreateRequestMarginStaticFromJSON(json['marginStatic']),
        'prestigeAmount': json['prestigeAmount'] == null ? undefined : ModifierCreateRequestMarginStaticFromJSON(json['prestigeAmount']),
        'printType': json['printType'] == null ? undefined : PrintTypeFromJSON(json['printType']),
        'categoryIds': json['categoryIds'] == null ? undefined : ((json['categoryIds'] as Array<any>).map(CashBoxesReadIdParameterFromJSON)),
        'modifierIds': json['modifierIds'] == null ? undefined : ((json['modifierIds'] as Array<any>).map(CashBoxesReadIdParameterFromJSON)),
    };
}

export function SaleItemUpdateModelToJSON(json: any): SaleItemUpdateModel {
    return SaleItemUpdateModelToJSONTyped(json, false);
}

export function SaleItemUpdateModelToJSONTyped(value?: SaleItemUpdateModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'image': value['image'],
        'marginPercent': ModifierCreateRequestMarginPercentToJSON(value['marginPercent']),
        'marginStatic': ModifierCreateRequestMarginStaticToJSON(value['marginStatic']),
        'prestigeAmount': ModifierCreateRequestMarginStaticToJSON(value['prestigeAmount']),
        'printType': PrintTypeToJSON(value['printType']),
        'categoryIds': value['categoryIds'] == null ? undefined : ((value['categoryIds'] as Array<any>).map(CashBoxesReadIdParameterToJSON)),
        'modifierIds': value['modifierIds'] == null ? undefined : ((value['modifierIds'] as Array<any>).map(CashBoxesReadIdParameterToJSON)),
    };
}

