/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CashBoxesReadIdParameter } from './CashBoxesReadIdParameter';
import {
    CashBoxesReadIdParameterFromJSON,
    CashBoxesReadIdParameterFromJSONTyped,
    CashBoxesReadIdParameterToJSON,
    CashBoxesReadIdParameterToJSONTyped,
} from './CashBoxesReadIdParameter';
import type { SaleItemOperatorModelAmountInStore } from './SaleItemOperatorModelAmountInStore';
import {
    SaleItemOperatorModelAmountInStoreFromJSON,
    SaleItemOperatorModelAmountInStoreFromJSONTyped,
    SaleItemOperatorModelAmountInStoreToJSON,
    SaleItemOperatorModelAmountInStoreToJSONTyped,
} from './SaleItemOperatorModelAmountInStore';
import type { AccountTransactionModelAmount } from './AccountTransactionModelAmount';
import {
    AccountTransactionModelAmountFromJSON,
    AccountTransactionModelAmountFromJSONTyped,
    AccountTransactionModelAmountToJSON,
    AccountTransactionModelAmountToJSONTyped,
} from './AccountTransactionModelAmount';

/**
 * 
 * @export
 * @interface SaleItemOperatorModel
 */
export interface SaleItemOperatorModel {
    /**
     * 
     * @type {CashBoxesReadIdParameter}
     * @memberof SaleItemOperatorModel
     */
    id: CashBoxesReadIdParameter;
    /**
     * 
     * @type {string}
     * @memberof SaleItemOperatorModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SaleItemOperatorModel
     */
    image: string | null;
    /**
     * 
     * @type {AccountTransactionModelAmount}
     * @memberof SaleItemOperatorModel
     */
    currentCost: AccountTransactionModelAmount;
    /**
     * 
     * @type {SaleItemOperatorModelAmountInStore}
     * @memberof SaleItemOperatorModel
     */
    amountInStore: SaleItemOperatorModelAmountInStore | null;
}

/**
 * Check if a given object implements the SaleItemOperatorModel interface.
 */
export function instanceOfSaleItemOperatorModel(value: object): value is SaleItemOperatorModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('currentCost' in value) || value['currentCost'] === undefined) return false;
    if (!('amountInStore' in value) || value['amountInStore'] === undefined) return false;
    return true;
}

export function SaleItemOperatorModelFromJSON(json: any): SaleItemOperatorModel {
    return SaleItemOperatorModelFromJSONTyped(json, false);
}

export function SaleItemOperatorModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaleItemOperatorModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': CashBoxesReadIdParameterFromJSON(json['id']),
        'name': json['name'],
        'image': json['image'],
        'currentCost': AccountTransactionModelAmountFromJSON(json['currentCost']),
        'amountInStore': SaleItemOperatorModelAmountInStoreFromJSON(json['amountInStore']),
    };
}

export function SaleItemOperatorModelToJSON(json: any): SaleItemOperatorModel {
    return SaleItemOperatorModelToJSONTyped(json, false);
}

export function SaleItemOperatorModelToJSONTyped(value?: SaleItemOperatorModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': CashBoxesReadIdParameterToJSON(value['id']),
        'name': value['name'],
        'image': value['image'],
        'currentCost': AccountTransactionModelAmountToJSON(value['currentCost']),
        'amountInStore': SaleItemOperatorModelAmountInStoreToJSON(value['amountInStore']),
    };
}

