/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CashBoxesReadIdParameter } from './CashBoxesReadIdParameter';
import {
    CashBoxesReadIdParameterFromJSON,
    CashBoxesReadIdParameterFromJSONTyped,
    CashBoxesReadIdParameterToJSON,
    CashBoxesReadIdParameterToJSONTyped,
} from './CashBoxesReadIdParameter';
import type { AccountTransactionModelAmount } from './AccountTransactionModelAmount';
import {
    AccountTransactionModelAmountFromJSON,
    AccountTransactionModelAmountFromJSONTyped,
    AccountTransactionModelAmountToJSON,
    AccountTransactionModelAmountToJSONTyped,
} from './AccountTransactionModelAmount';

/**
 * 
 * @export
 * @interface SaleTransactionCloseRequestModel
 */
export interface SaleTransactionCloseRequestModel {
    /**
     * 
     * @type {string}
     * @memberof SaleTransactionCloseRequestModel
     */
    note?: string | null;
    /**
     * 
     * @type {CashBoxesReadIdParameter}
     * @memberof SaleTransactionCloseRequestModel
     */
    cashBoxId: CashBoxesReadIdParameter;
    /**
     * 
     * @type {CashBoxesReadIdParameter}
     * @memberof SaleTransactionCloseRequestModel
     */
    customerId: CashBoxesReadIdParameter;
    /**
     * 
     * @type {AccountTransactionModelAmount}
     * @memberof SaleTransactionCloseRequestModel
     */
    paidAmount: AccountTransactionModelAmount;
}

/**
 * Check if a given object implements the SaleTransactionCloseRequestModel interface.
 */
export function instanceOfSaleTransactionCloseRequestModel(value: object): value is SaleTransactionCloseRequestModel {
    if (!('cashBoxId' in value) || value['cashBoxId'] === undefined) return false;
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('paidAmount' in value) || value['paidAmount'] === undefined) return false;
    return true;
}

export function SaleTransactionCloseRequestModelFromJSON(json: any): SaleTransactionCloseRequestModel {
    return SaleTransactionCloseRequestModelFromJSONTyped(json, false);
}

export function SaleTransactionCloseRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaleTransactionCloseRequestModel {
    if (json == null) {
        return json;
    }
    return {
        
        'note': json['note'] == null ? undefined : json['note'],
        'cashBoxId': CashBoxesReadIdParameterFromJSON(json['cashBoxId']),
        'customerId': CashBoxesReadIdParameterFromJSON(json['customerId']),
        'paidAmount': AccountTransactionModelAmountFromJSON(json['paidAmount']),
    };
}

export function SaleTransactionCloseRequestModelToJSON(json: any): SaleTransactionCloseRequestModel {
    return SaleTransactionCloseRequestModelToJSONTyped(json, false);
}

export function SaleTransactionCloseRequestModelToJSONTyped(value?: SaleTransactionCloseRequestModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'note': value['note'],
        'cashBoxId': CashBoxesReadIdParameterToJSON(value['cashBoxId']),
        'customerId': CashBoxesReadIdParameterToJSON(value['customerId']),
        'paidAmount': AccountTransactionModelAmountToJSON(value['paidAmount']),
    };
}

