/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaleItemOperatorModelAmountInStore
 */
export interface SaleItemOperatorModelAmountInStore {
}

/**
 * Check if a given object implements the SaleItemOperatorModelAmountInStore interface.
 */
export function instanceOfSaleItemOperatorModelAmountInStore(value: object): value is SaleItemOperatorModelAmountInStore {
    return true;
}

export function SaleItemOperatorModelAmountInStoreFromJSON(json: any): SaleItemOperatorModelAmountInStore {
    return SaleItemOperatorModelAmountInStoreFromJSONTyped(json, false);
}

export function SaleItemOperatorModelAmountInStoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaleItemOperatorModelAmountInStore {
    return json;
}

export function SaleItemOperatorModelAmountInStoreToJSON(json: any): SaleItemOperatorModelAmountInStore {
    return SaleItemOperatorModelAmountInStoreToJSONTyped(json, false);
}

export function SaleItemOperatorModelAmountInStoreToJSONTyped(value?: SaleItemOperatorModelAmountInStore | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

