/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SaleTransactionItemCreateRequest } from './SaleTransactionItemCreateRequest';
import {
    SaleTransactionItemCreateRequestFromJSON,
    SaleTransactionItemCreateRequestFromJSONTyped,
    SaleTransactionItemCreateRequestToJSON,
    SaleTransactionItemCreateRequestToJSONTyped,
} from './SaleTransactionItemCreateRequest';

/**
 * 
 * @export
 * @interface SaleTransactionCreateRequest
 */
export interface SaleTransactionCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof SaleTransactionCreateRequest
     */
    note?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SaleTransactionCreateRequest
     */
    storeId: number;
    /**
     * 
     * @type {number}
     * @memberof SaleTransactionCreateRequest
     */
    cashBoxId: number;
    /**
     * 
     * @type {number}
     * @memberof SaleTransactionCreateRequest
     */
    customerId: number;
    /**
     * 
     * @type {string}
     * @memberof SaleTransactionCreateRequest
     */
    paidAmount: string;
    /**
     * 
     * @type {Array<SaleTransactionItemCreateRequest>}
     * @memberof SaleTransactionCreateRequest
     */
    saleTransactionItems?: Array<SaleTransactionItemCreateRequest>;
}

/**
 * Check if a given object implements the SaleTransactionCreateRequest interface.
 */
export function instanceOfSaleTransactionCreateRequest(value: object): value is SaleTransactionCreateRequest {
    if (!('storeId' in value) || value['storeId'] === undefined) return false;
    if (!('cashBoxId' in value) || value['cashBoxId'] === undefined) return false;
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('paidAmount' in value) || value['paidAmount'] === undefined) return false;
    return true;
}

export function SaleTransactionCreateRequestFromJSON(json: any): SaleTransactionCreateRequest {
    return SaleTransactionCreateRequestFromJSONTyped(json, false);
}

export function SaleTransactionCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaleTransactionCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'note': json['note'] == null ? undefined : json['note'],
        'storeId': json['storeId'],
        'cashBoxId': json['cashBoxId'],
        'customerId': json['customerId'],
        'paidAmount': json['paidAmount'],
        'saleTransactionItems': json['saleTransactionItems'] == null ? undefined : ((json['saleTransactionItems'] as Array<any>).map(SaleTransactionItemCreateRequestFromJSON)),
    };
}

export function SaleTransactionCreateRequestToJSON(json: any): SaleTransactionCreateRequest {
    return SaleTransactionCreateRequestToJSONTyped(json, false);
}

export function SaleTransactionCreateRequestToJSONTyped(value?: SaleTransactionCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'note': value['note'],
        'storeId': value['storeId'],
        'cashBoxId': value['cashBoxId'],
        'customerId': value['customerId'],
        'paidAmount': value['paidAmount'],
        'saleTransactionItems': value['saleTransactionItems'] == null ? undefined : ((value['saleTransactionItems'] as Array<any>).map(SaleTransactionItemCreateRequestToJSON)),
    };
}

