/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaleTransactionCloseRequestModel
 */
export interface SaleTransactionCloseRequestModel {
    /**
     * 
     * @type {string}
     * @memberof SaleTransactionCloseRequestModel
     */
    note?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SaleTransactionCloseRequestModel
     */
    cashBoxId: number;
    /**
     * 
     * @type {number}
     * @memberof SaleTransactionCloseRequestModel
     */
    customerId: number;
    /**
     * 
     * @type {string}
     * @memberof SaleTransactionCloseRequestModel
     */
    paidAmount: string;
}

/**
 * Check if a given object implements the SaleTransactionCloseRequestModel interface.
 */
export function instanceOfSaleTransactionCloseRequestModel(value: object): value is SaleTransactionCloseRequestModel {
    if (!('cashBoxId' in value) || value['cashBoxId'] === undefined) return false;
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('paidAmount' in value) || value['paidAmount'] === undefined) return false;
    return true;
}

export function SaleTransactionCloseRequestModelFromJSON(json: any): SaleTransactionCloseRequestModel {
    return SaleTransactionCloseRequestModelFromJSONTyped(json, false);
}

export function SaleTransactionCloseRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaleTransactionCloseRequestModel {
    if (json == null) {
        return json;
    }
    return {
        
        'note': json['note'] == null ? undefined : json['note'],
        'cashBoxId': json['cashBoxId'],
        'customerId': json['customerId'],
        'paidAmount': json['paidAmount'],
    };
}

export function SaleTransactionCloseRequestModelToJSON(json: any): SaleTransactionCloseRequestModel {
    return SaleTransactionCloseRequestModelToJSONTyped(json, false);
}

export function SaleTransactionCloseRequestModelToJSONTyped(value?: SaleTransactionCloseRequestModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'note': value['note'],
        'cashBoxId': value['cashBoxId'],
        'customerId': value['customerId'],
        'paidAmount': value['paidAmount'],
    };
}

