/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SaleTransactionItemCreateRequest } from './SaleTransactionItemCreateRequest';
import {
    SaleTransactionItemCreateRequestFromJSON,
    SaleTransactionItemCreateRequestFromJSONTyped,
    SaleTransactionItemCreateRequestToJSON,
    SaleTransactionItemCreateRequestToJSONTyped,
} from './SaleTransactionItemCreateRequest';

/**
 * 
 * @export
 * @interface SaleTransactionOpenRequest
 */
export interface SaleTransactionOpenRequest {
    /**
     * 
     * @type {string}
     * @memberof SaleTransactionOpenRequest
     */
    note?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SaleTransactionOpenRequest
     */
    storeId: number;
    /**
     * 
     * @type {Array<SaleTransactionItemCreateRequest>}
     * @memberof SaleTransactionOpenRequest
     */
    saleTransactionItems?: Array<SaleTransactionItemCreateRequest>;
}

/**
 * Check if a given object implements the SaleTransactionOpenRequest interface.
 */
export function instanceOfSaleTransactionOpenRequest(value: object): value is SaleTransactionOpenRequest {
    if (!('storeId' in value) || value['storeId'] === undefined) return false;
    return true;
}

export function SaleTransactionOpenRequestFromJSON(json: any): SaleTransactionOpenRequest {
    return SaleTransactionOpenRequestFromJSONTyped(json, false);
}

export function SaleTransactionOpenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaleTransactionOpenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'note': json['note'] == null ? undefined : json['note'],
        'storeId': json['storeId'],
        'saleTransactionItems': json['saleTransactionItems'] == null ? undefined : ((json['saleTransactionItems'] as Array<any>).map(SaleTransactionItemCreateRequestFromJSON)),
    };
}

export function SaleTransactionOpenRequestToJSON(json: any): SaleTransactionOpenRequest {
    return SaleTransactionOpenRequestToJSONTyped(json, false);
}

export function SaleTransactionOpenRequestToJSONTyped(value?: SaleTransactionOpenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'note': value['note'],
        'storeId': value['storeId'],
        'saleTransactionItems': value['saleTransactionItems'] == null ? undefined : ((value['saleTransactionItems'] as Array<any>).map(SaleTransactionItemCreateRequestToJSON)),
    };
}

