/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PrintType } from './PrintType';
import {
    PrintTypeFromJSON,
    PrintTypeFromJSONTyped,
    PrintTypeToJSON,
    PrintTypeToJSONTyped,
} from './PrintType';

/**
 * 
 * @export
 * @interface SaleItemListModel
 */
export interface SaleItemListModel {
    /**
     * 
     * @type {number}
     * @memberof SaleItemListModel
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof SaleItemListModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SaleItemListModel
     */
    image: string | null;
    /**
     * 
     * @type {string}
     * @memberof SaleItemListModel
     */
    marginPercent: string;
    /**
     * 
     * @type {string}
     * @memberof SaleItemListModel
     */
    marginStatic: string;
    /**
     * 
     * @type {string}
     * @memberof SaleItemListModel
     */
    prestigeAmount: string;
    /**
     * 
     * @type {PrintType}
     * @memberof SaleItemListModel
     */
    printType: PrintType;
}



/**
 * Check if a given object implements the SaleItemListModel interface.
 */
export function instanceOfSaleItemListModel(value: object): value is SaleItemListModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('marginPercent' in value) || value['marginPercent'] === undefined) return false;
    if (!('marginStatic' in value) || value['marginStatic'] === undefined) return false;
    if (!('prestigeAmount' in value) || value['prestigeAmount'] === undefined) return false;
    if (!('printType' in value) || value['printType'] === undefined) return false;
    return true;
}

export function SaleItemListModelFromJSON(json: any): SaleItemListModel {
    return SaleItemListModelFromJSONTyped(json, false);
}

export function SaleItemListModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaleItemListModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'image': json['image'],
        'marginPercent': json['marginPercent'],
        'marginStatic': json['marginStatic'],
        'prestigeAmount': json['prestigeAmount'],
        'printType': PrintTypeFromJSON(json['printType']),
    };
}

export function SaleItemListModelToJSON(json: any): SaleItemListModel {
    return SaleItemListModelToJSONTyped(json, false);
}

export function SaleItemListModelToJSONTyped(value?: SaleItemListModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'image': value['image'],
        'marginPercent': value['marginPercent'],
        'marginStatic': value['marginStatic'],
        'prestigeAmount': value['prestigeAmount'],
        'printType': PrintTypeToJSON(value['printType']),
    };
}

