/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SaleTransactionItemModel } from './SaleTransactionItemModel';
import {
    SaleTransactionItemModelFromJSON,
    SaleTransactionItemModelFromJSONTyped,
    SaleTransactionItemModelToJSON,
    SaleTransactionItemModelToJSONTyped,
} from './SaleTransactionItemModel';

/**
 * 
 * @export
 * @interface SaleTransactionCheckPriceResponse
 */
export interface SaleTransactionCheckPriceResponse {
    /**
     * 
     * @type {Array<SaleTransactionItemModel>}
     * @memberof SaleTransactionCheckPriceResponse
     */
    saleTransactionItems: Array<SaleTransactionItemModel>;
}

/**
 * Check if a given object implements the SaleTransactionCheckPriceResponse interface.
 */
export function instanceOfSaleTransactionCheckPriceResponse(value: object): value is SaleTransactionCheckPriceResponse {
    if (!('saleTransactionItems' in value) || value['saleTransactionItems'] === undefined) return false;
    return true;
}

export function SaleTransactionCheckPriceResponseFromJSON(json: any): SaleTransactionCheckPriceResponse {
    return SaleTransactionCheckPriceResponseFromJSONTyped(json, false);
}

export function SaleTransactionCheckPriceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaleTransactionCheckPriceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'saleTransactionItems': ((json['saleTransactionItems'] as Array<any>).map(SaleTransactionItemModelFromJSON)),
    };
}

export function SaleTransactionCheckPriceResponseToJSON(json: any): SaleTransactionCheckPriceResponse {
    return SaleTransactionCheckPriceResponseToJSONTyped(json, false);
}

export function SaleTransactionCheckPriceResponseToJSONTyped(value?: SaleTransactionCheckPriceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'saleTransactionItems': ((value['saleTransactionItems'] as Array<any>).map(SaleTransactionItemModelToJSON)),
    };
}

