/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SaleItemListModel } from './SaleItemListModel';
import {
    SaleItemListModelFromJSON,
    SaleItemListModelFromJSONTyped,
    SaleItemListModelToJSON,
    SaleItemListModelToJSONTyped,
} from './SaleItemListModel';
import type { PageMeta } from './PageMeta';
import {
    PageMetaFromJSON,
    PageMetaFromJSONTyped,
    PageMetaToJSON,
    PageMetaToJSONTyped,
} from './PageMeta';

/**
 * 
 * @export
 * @interface SaleItemReadAllResponse
 */
export interface SaleItemReadAllResponse {
    /**
     * 
     * @type {Array<SaleItemListModel>}
     * @memberof SaleItemReadAllResponse
     */
    data: Array<SaleItemListModel>;
    /**
     * 
     * @type {PageMeta}
     * @memberof SaleItemReadAllResponse
     */
    meta: PageMeta;
}

/**
 * Check if a given object implements the SaleItemReadAllResponse interface.
 */
export function instanceOfSaleItemReadAllResponse(value: object): value is SaleItemReadAllResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function SaleItemReadAllResponseFromJSON(json: any): SaleItemReadAllResponse {
    return SaleItemReadAllResponseFromJSONTyped(json, false);
}

export function SaleItemReadAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaleItemReadAllResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(SaleItemListModelFromJSON)),
        'meta': PageMetaFromJSON(json['meta']),
    };
}

export function SaleItemReadAllResponseToJSON(json: any): SaleItemReadAllResponse {
    return SaleItemReadAllResponseToJSONTyped(json, false);
}

export function SaleItemReadAllResponseToJSONTyped(value?: SaleItemReadAllResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(SaleItemListModelToJSON)),
        'meta': PageMetaToJSON(value['meta']),
    };
}

