/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PrintType } from './PrintType';
import {
    PrintTypeFromJSON,
    PrintTypeFromJSONTyped,
    PrintTypeToJSON,
    PrintTypeToJSONTyped,
} from './PrintType';
import type { ModifierListModel } from './ModifierListModel';
import {
    ModifierListModelFromJSON,
    ModifierListModelFromJSONTyped,
    ModifierListModelToJSON,
    ModifierListModelToJSONTyped,
} from './ModifierListModel';
import type { CashBoxesReadIdParameter } from './CashBoxesReadIdParameter';
import {
    CashBoxesReadIdParameterFromJSON,
    CashBoxesReadIdParameterFromJSONTyped,
    CashBoxesReadIdParameterToJSON,
    CashBoxesReadIdParameterToJSONTyped,
} from './CashBoxesReadIdParameter';
import type { CategoryModel } from './CategoryModel';
import {
    CategoryModelFromJSON,
    CategoryModelFromJSONTyped,
    CategoryModelToJSON,
    CategoryModelToJSONTyped,
} from './CategoryModel';
import type { AccountTransactionModelAmount } from './AccountTransactionModelAmount';
import {
    AccountTransactionModelAmountFromJSON,
    AccountTransactionModelAmountFromJSONTyped,
    AccountTransactionModelAmountToJSON,
    AccountTransactionModelAmountToJSONTyped,
} from './AccountTransactionModelAmount';

/**
 * 
 * @export
 * @interface SaleItemUpdateResponse
 */
export interface SaleItemUpdateResponse {
    /**
     * 
     * @type {CashBoxesReadIdParameter}
     * @memberof SaleItemUpdateResponse
     */
    id: CashBoxesReadIdParameter;
    /**
     * 
     * @type {string}
     * @memberof SaleItemUpdateResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SaleItemUpdateResponse
     */
    image: string | null;
    /**
     * 
     * @type {AccountTransactionModelAmount}
     * @memberof SaleItemUpdateResponse
     */
    marginPercent: AccountTransactionModelAmount;
    /**
     * 
     * @type {AccountTransactionModelAmount}
     * @memberof SaleItemUpdateResponse
     */
    marginStatic: AccountTransactionModelAmount;
    /**
     * 
     * @type {AccountTransactionModelAmount}
     * @memberof SaleItemUpdateResponse
     */
    prestigeAmount: AccountTransactionModelAmount;
    /**
     * 
     * @type {PrintType}
     * @memberof SaleItemUpdateResponse
     */
    printType: PrintType;
    /**
     * 
     * @type {Array<ModifierListModel>}
     * @memberof SaleItemUpdateResponse
     */
    applicableModifiers: Array<ModifierListModel>;
    /**
     * 
     * @type {Array<CategoryModel>}
     * @memberof SaleItemUpdateResponse
     */
    categories: Array<CategoryModel>;
}



/**
 * Check if a given object implements the SaleItemUpdateResponse interface.
 */
export function instanceOfSaleItemUpdateResponse(value: object): value is SaleItemUpdateResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('marginPercent' in value) || value['marginPercent'] === undefined) return false;
    if (!('marginStatic' in value) || value['marginStatic'] === undefined) return false;
    if (!('prestigeAmount' in value) || value['prestigeAmount'] === undefined) return false;
    if (!('printType' in value) || value['printType'] === undefined) return false;
    if (!('applicableModifiers' in value) || value['applicableModifiers'] === undefined) return false;
    if (!('categories' in value) || value['categories'] === undefined) return false;
    return true;
}

export function SaleItemUpdateResponseFromJSON(json: any): SaleItemUpdateResponse {
    return SaleItemUpdateResponseFromJSONTyped(json, false);
}

export function SaleItemUpdateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaleItemUpdateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': CashBoxesReadIdParameterFromJSON(json['id']),
        'name': json['name'],
        'image': json['image'],
        'marginPercent': AccountTransactionModelAmountFromJSON(json['marginPercent']),
        'marginStatic': AccountTransactionModelAmountFromJSON(json['marginStatic']),
        'prestigeAmount': AccountTransactionModelAmountFromJSON(json['prestigeAmount']),
        'printType': PrintTypeFromJSON(json['printType']),
        'applicableModifiers': ((json['applicableModifiers'] as Array<any>).map(ModifierListModelFromJSON)),
        'categories': ((json['categories'] as Array<any>).map(CategoryModelFromJSON)),
    };
}

export function SaleItemUpdateResponseToJSON(json: any): SaleItemUpdateResponse {
    return SaleItemUpdateResponseToJSONTyped(json, false);
}

export function SaleItemUpdateResponseToJSONTyped(value?: SaleItemUpdateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': CashBoxesReadIdParameterToJSON(value['id']),
        'name': value['name'],
        'image': value['image'],
        'marginPercent': AccountTransactionModelAmountToJSON(value['marginPercent']),
        'marginStatic': AccountTransactionModelAmountToJSON(value['marginStatic']),
        'prestigeAmount': AccountTransactionModelAmountToJSON(value['prestigeAmount']),
        'printType': PrintTypeToJSON(value['printType']),
        'applicableModifiers': ((value['applicableModifiers'] as Array<any>).map(ModifierListModelToJSON)),
        'categories': ((value['categories'] as Array<any>).map(CategoryModelToJSON)),
    };
}

