/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StoreListModel } from './StoreListModel';
import {
    StoreListModelFromJSON,
    StoreListModelFromJSONTyped,
    StoreListModelToJSON,
    StoreListModelToJSONTyped,
} from './StoreListModel';
import type { StoreItemListModel } from './StoreItemListModel';
import {
    StoreItemListModelFromJSON,
    StoreItemListModelFromJSONTyped,
    StoreItemListModelToJSON,
    StoreItemListModelToJSONTyped,
} from './StoreItemListModel';
import type { CashBoxesReadIdParameter } from './CashBoxesReadIdParameter';
import {
    CashBoxesReadIdParameterFromJSON,
    CashBoxesReadIdParameterFromJSONTyped,
    CashBoxesReadIdParameterToJSON,
    CashBoxesReadIdParameterToJSONTyped,
} from './CashBoxesReadIdParameter';
import type { AccountTransactionModelAmount } from './AccountTransactionModelAmount';
import {
    AccountTransactionModelAmountFromJSON,
    AccountTransactionModelAmountFromJSONTyped,
    AccountTransactionModelAmountToJSON,
    AccountTransactionModelAmountToJSONTyped,
} from './AccountTransactionModelAmount';

/**
 * 
 * @export
 * @interface StoreTransactionItemModel
 */
export interface StoreTransactionItemModel {
    /**
     * 
     * @type {AccountTransactionModelAmount}
     * @memberof StoreTransactionItemModel
     */
    itemAmount: AccountTransactionModelAmount;
    /**
     * 
     * @type {AccountTransactionModelAmount}
     * @memberof StoreTransactionItemModel
     */
    cost: AccountTransactionModelAmount;
    /**
     * 
     * @type {StoreItemListModel}
     * @memberof StoreTransactionItemModel
     */
    storeItem: StoreItemListModel;
    /**
     * 
     * @type {StoreListModel}
     * @memberof StoreTransactionItemModel
     */
    store: StoreListModel;
    /**
     * 
     * @type {CashBoxesReadIdParameter}
     * @memberof StoreTransactionItemModel
     */
    storeTransactionId: CashBoxesReadIdParameter;
}

/**
 * Check if a given object implements the StoreTransactionItemModel interface.
 */
export function instanceOfStoreTransactionItemModel(value: object): value is StoreTransactionItemModel {
    if (!('itemAmount' in value) || value['itemAmount'] === undefined) return false;
    if (!('cost' in value) || value['cost'] === undefined) return false;
    if (!('storeItem' in value) || value['storeItem'] === undefined) return false;
    if (!('store' in value) || value['store'] === undefined) return false;
    if (!('storeTransactionId' in value) || value['storeTransactionId'] === undefined) return false;
    return true;
}

export function StoreTransactionItemModelFromJSON(json: any): StoreTransactionItemModel {
    return StoreTransactionItemModelFromJSONTyped(json, false);
}

export function StoreTransactionItemModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreTransactionItemModel {
    if (json == null) {
        return json;
    }
    return {
        
        'itemAmount': AccountTransactionModelAmountFromJSON(json['itemAmount']),
        'cost': AccountTransactionModelAmountFromJSON(json['cost']),
        'storeItem': StoreItemListModelFromJSON(json['storeItem']),
        'store': StoreListModelFromJSON(json['store']),
        'storeTransactionId': CashBoxesReadIdParameterFromJSON(json['storeTransactionId']),
    };
}

export function StoreTransactionItemModelToJSON(json: any): StoreTransactionItemModel {
    return StoreTransactionItemModelToJSONTyped(json, false);
}

export function StoreTransactionItemModelToJSONTyped(value?: StoreTransactionItemModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itemAmount': AccountTransactionModelAmountToJSON(value['itemAmount']),
        'cost': AccountTransactionModelAmountToJSON(value['cost']),
        'storeItem': StoreItemListModelToJSON(value['storeItem']),
        'store': StoreListModelToJSON(value['store']),
        'storeTransactionId': CashBoxesReadIdParameterToJSON(value['storeTransactionId']),
    };
}

