/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StoreUpdateRequest
 */
export interface StoreUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof StoreUpdateRequest
     */
    name: string;
}

/**
 * Check if a given object implements the StoreUpdateRequest interface.
 */
export function instanceOfStoreUpdateRequest(value: object): value is StoreUpdateRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function StoreUpdateRequestFromJSON(json: any): StoreUpdateRequest {
    return StoreUpdateRequestFromJSONTyped(json, false);
}

export function StoreUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function StoreUpdateRequestToJSON(json: any): StoreUpdateRequest {
    return StoreUpdateRequestToJSONTyped(json, false);
}

export function StoreUpdateRequestToJSONTyped(value?: StoreUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

