/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CashBoxesReadIdParameter } from './CashBoxesReadIdParameter';
import {
    CashBoxesReadIdParameterFromJSON,
    CashBoxesReadIdParameterFromJSONTyped,
    CashBoxesReadIdParameterToJSON,
    CashBoxesReadIdParameterToJSONTyped,
} from './CashBoxesReadIdParameter';

/**
 * 
 * @export
 * @interface StoreUpdateResponse
 */
export interface StoreUpdateResponse {
    /**
     * 
     * @type {CashBoxesReadIdParameter}
     * @memberof StoreUpdateResponse
     */
    id: CashBoxesReadIdParameter;
    /**
     * 
     * @type {string}
     * @memberof StoreUpdateResponse
     */
    name: string;
}

/**
 * Check if a given object implements the StoreUpdateResponse interface.
 */
export function instanceOfStoreUpdateResponse(value: object): value is StoreUpdateResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function StoreUpdateResponseFromJSON(json: any): StoreUpdateResponse {
    return StoreUpdateResponseFromJSONTyped(json, false);
}

export function StoreUpdateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreUpdateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': CashBoxesReadIdParameterFromJSON(json['id']),
        'name': json['name'],
    };
}

export function StoreUpdateResponseToJSON(json: any): StoreUpdateResponse {
    return StoreUpdateResponseToJSONTyped(json, false);
}

export function StoreUpdateResponseToJSONTyped(value?: StoreUpdateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': CashBoxesReadIdParameterToJSON(value['id']),
        'name': value['name'],
    };
}

