/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CashBoxesReadIdParameter } from './CashBoxesReadIdParameter';
import {
    CashBoxesReadIdParameterFromJSON,
    CashBoxesReadIdParameterFromJSONTyped,
    CashBoxesReadIdParameterToJSON,
    CashBoxesReadIdParameterToJSONTyped,
} from './CashBoxesReadIdParameter';
import type { AccountTransactionModelAmount } from './AccountTransactionModelAmount';
import {
    AccountTransactionModelAmountFromJSON,
    AccountTransactionModelAmountFromJSONTyped,
    AccountTransactionModelAmountToJSON,
    AccountTransactionModelAmountToJSONTyped,
} from './AccountTransactionModelAmount';

/**
 * 
 * @export
 * @interface StoreTransactionItemCreateRequest
 */
export interface StoreTransactionItemCreateRequest {
    /**
     * 
     * @type {AccountTransactionModelAmount}
     * @memberof StoreTransactionItemCreateRequest
     */
    itemAmount: AccountTransactionModelAmount;
    /**
     * 
     * @type {AccountTransactionModelAmount}
     * @memberof StoreTransactionItemCreateRequest
     */
    cost: AccountTransactionModelAmount;
    /**
     * 
     * @type {CashBoxesReadIdParameter}
     * @memberof StoreTransactionItemCreateRequest
     */
    storeItemId: CashBoxesReadIdParameter;
}

/**
 * Check if a given object implements the StoreTransactionItemCreateRequest interface.
 */
export function instanceOfStoreTransactionItemCreateRequest(value: object): value is StoreTransactionItemCreateRequest {
    if (!('itemAmount' in value) || value['itemAmount'] === undefined) return false;
    if (!('cost' in value) || value['cost'] === undefined) return false;
    if (!('storeItemId' in value) || value['storeItemId'] === undefined) return false;
    return true;
}

export function StoreTransactionItemCreateRequestFromJSON(json: any): StoreTransactionItemCreateRequest {
    return StoreTransactionItemCreateRequestFromJSONTyped(json, false);
}

export function StoreTransactionItemCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreTransactionItemCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'itemAmount': AccountTransactionModelAmountFromJSON(json['itemAmount']),
        'cost': AccountTransactionModelAmountFromJSON(json['cost']),
        'storeItemId': CashBoxesReadIdParameterFromJSON(json['storeItemId']),
    };
}

export function StoreTransactionItemCreateRequestToJSON(json: any): StoreTransactionItemCreateRequest {
    return StoreTransactionItemCreateRequestToJSONTyped(json, false);
}

export function StoreTransactionItemCreateRequestToJSONTyped(value?: StoreTransactionItemCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itemAmount': AccountTransactionModelAmountToJSON(value['itemAmount']),
        'cost': AccountTransactionModelAmountToJSON(value['cost']),
        'storeItemId': CashBoxesReadIdParameterToJSON(value['storeItemId']),
    };
}

