/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StoreTransactionItemModel } from './StoreTransactionItemModel';
import {
    StoreTransactionItemModelFromJSON,
    StoreTransactionItemModelFromJSONTyped,
    StoreTransactionItemModelToJSON,
    StoreTransactionItemModelToJSONTyped,
} from './StoreTransactionItemModel';
import type { TransactionReason } from './TransactionReason';
import {
    TransactionReasonFromJSON,
    TransactionReasonFromJSONTyped,
    TransactionReasonToJSON,
    TransactionReasonToJSONTyped,
} from './TransactionReason';
import type { UserListModel } from './UserListModel';
import {
    UserListModelFromJSON,
    UserListModelFromJSONTyped,
    UserListModelToJSON,
    UserListModelToJSONTyped,
} from './UserListModel';

/**
 * 
 * @export
 * @interface StoreTransactionReadResponse
 */
export interface StoreTransactionReadResponse {
    /**
     * 
     * @type {number}
     * @memberof StoreTransactionReadResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof StoreTransactionReadResponse
     */
    note: string | null;
    /**
     * 
     * @type {Date}
     * @memberof StoreTransactionReadResponse
     */
    startedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof StoreTransactionReadResponse
     */
    cancelledAt: Date | null;
    /**
     * 
     * @type {UserListModel}
     * @memberof StoreTransactionReadResponse
     */
    startedBy: UserListModel;
    /**
     * 
     * @type {UserListModel}
     * @memberof StoreTransactionReadResponse
     */
    cancelledBy: UserListModel | null;
    /**
     * 
     * @type {TransactionReason}
     * @memberof StoreTransactionReadResponse
     */
    reason: TransactionReason;
    /**
     * 
     * @type {number}
     * @memberof StoreTransactionReadResponse
     */
    saleTransactionId: number;
    /**
     * 
     * @type {Array<StoreTransactionItemModel>}
     * @memberof StoreTransactionReadResponse
     */
    storeTransactionItems: Array<StoreTransactionItemModel>;
}



/**
 * Check if a given object implements the StoreTransactionReadResponse interface.
 */
export function instanceOfStoreTransactionReadResponse(value: object): value is StoreTransactionReadResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('note' in value) || value['note'] === undefined) return false;
    if (!('startedAt' in value) || value['startedAt'] === undefined) return false;
    if (!('cancelledAt' in value) || value['cancelledAt'] === undefined) return false;
    if (!('startedBy' in value) || value['startedBy'] === undefined) return false;
    if (!('cancelledBy' in value) || value['cancelledBy'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('saleTransactionId' in value) || value['saleTransactionId'] === undefined) return false;
    if (!('storeTransactionItems' in value) || value['storeTransactionItems'] === undefined) return false;
    return true;
}

export function StoreTransactionReadResponseFromJSON(json: any): StoreTransactionReadResponse {
    return StoreTransactionReadResponseFromJSONTyped(json, false);
}

export function StoreTransactionReadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreTransactionReadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'note': json['note'],
        'startedAt': (new Date(json['startedAt'])),
        'cancelledAt': (json['cancelledAt'] == null ? null : new Date(json['cancelledAt'])),
        'startedBy': UserListModelFromJSON(json['startedBy']),
        'cancelledBy': UserListModelFromJSON(json['cancelledBy']),
        'reason': TransactionReasonFromJSON(json['reason']),
        'saleTransactionId': json['saleTransactionId'],
        'storeTransactionItems': ((json['storeTransactionItems'] as Array<any>).map(StoreTransactionItemModelFromJSON)),
    };
}

export function StoreTransactionReadResponseToJSON(json: any): StoreTransactionReadResponse {
    return StoreTransactionReadResponseToJSONTyped(json, false);
}

export function StoreTransactionReadResponseToJSONTyped(value?: StoreTransactionReadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'note': value['note'],
        'startedAt': value['startedAt'].toISOString(),
        'cancelledAt': value['cancelledAt'] == null ? value['cancelledAt'] : value['cancelledAt'].toISOString(),
        'startedBy': UserListModelToJSON(value['startedBy']),
        'cancelledBy': UserListModelToJSON(value['cancelledBy']),
        'reason': TransactionReasonToJSON(value['reason']),
        'saleTransactionId': value['saleTransactionId'],
        'storeTransactionItems': ((value['storeTransactionItems'] as Array<any>).map(StoreTransactionItemModelToJSON)),
    };
}

