/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMeta } from './PageMeta';
import {
    PageMetaFromJSON,
    PageMetaFromJSONTyped,
    PageMetaToJSON,
    PageMetaToJSONTyped,
} from './PageMeta';
import type { StoreItemAmountModel } from './StoreItemAmountModel';
import {
    StoreItemAmountModelFromJSON,
    StoreItemAmountModelFromJSONTyped,
    StoreItemAmountModelToJSON,
    StoreItemAmountModelToJSONTyped,
} from './StoreItemAmountModel';

/**
 * 
 * @export
 * @interface StoreItemAmountReadAllResponse
 */
export interface StoreItemAmountReadAllResponse {
    /**
     * 
     * @type {Array<StoreItemAmountModel>}
     * @memberof StoreItemAmountReadAllResponse
     */
    data: Array<StoreItemAmountModel>;
    /**
     * 
     * @type {PageMeta}
     * @memberof StoreItemAmountReadAllResponse
     */
    meta: PageMeta;
}

/**
 * Check if a given object implements the StoreItemAmountReadAllResponse interface.
 */
export function instanceOfStoreItemAmountReadAllResponse(value: object): value is StoreItemAmountReadAllResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function StoreItemAmountReadAllResponseFromJSON(json: any): StoreItemAmountReadAllResponse {
    return StoreItemAmountReadAllResponseFromJSONTyped(json, false);
}

export function StoreItemAmountReadAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreItemAmountReadAllResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(StoreItemAmountModelFromJSON)),
        'meta': PageMetaFromJSON(json['meta']),
    };
}

export function StoreItemAmountReadAllResponseToJSON(json: any): StoreItemAmountReadAllResponse {
    return StoreItemAmountReadAllResponseToJSONTyped(json, false);
}

export function StoreItemAmountReadAllResponseToJSONTyped(value?: StoreItemAmountReadAllResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(StoreItemAmountModelToJSON)),
        'meta': PageMetaToJSON(value['meta']),
    };
}

