/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMeta } from './PageMeta';
import {
    PageMetaFromJSON,
    PageMetaFromJSONTyped,
    PageMetaToJSON,
    PageMetaToJSONTyped,
} from './PageMeta';
import type { StoreTransactionListModel } from './StoreTransactionListModel';
import {
    StoreTransactionListModelFromJSON,
    StoreTransactionListModelFromJSONTyped,
    StoreTransactionListModelToJSON,
    StoreTransactionListModelToJSONTyped,
} from './StoreTransactionListModel';

/**
 * 
 * @export
 * @interface StoreTransactionReadAllResponse
 */
export interface StoreTransactionReadAllResponse {
    /**
     * 
     * @type {Array<StoreTransactionListModel>}
     * @memberof StoreTransactionReadAllResponse
     */
    data: Array<StoreTransactionListModel>;
    /**
     * 
     * @type {PageMeta}
     * @memberof StoreTransactionReadAllResponse
     */
    meta: PageMeta;
}

/**
 * Check if a given object implements the StoreTransactionReadAllResponse interface.
 */
export function instanceOfStoreTransactionReadAllResponse(value: object): value is StoreTransactionReadAllResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function StoreTransactionReadAllResponseFromJSON(json: any): StoreTransactionReadAllResponse {
    return StoreTransactionReadAllResponseFromJSONTyped(json, false);
}

export function StoreTransactionReadAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreTransactionReadAllResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(StoreTransactionListModelFromJSON)),
        'meta': PageMetaFromJSON(json['meta']),
    };
}

export function StoreTransactionReadAllResponseToJSON(json: any): StoreTransactionReadAllResponse {
    return StoreTransactionReadAllResponseToJSONTyped(json, false);
}

export function StoreTransactionReadAllResponseToJSONTyped(value?: StoreTransactionReadAllResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(StoreTransactionListModelToJSON)),
        'meta': PageMetaToJSON(value['meta']),
    };
}

