/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CashBoxesReadIdParameter } from './CashBoxesReadIdParameter';
import {
    CashBoxesReadIdParameterFromJSON,
    CashBoxesReadIdParameterFromJSONTyped,
    CashBoxesReadIdParameterToJSON,
    CashBoxesReadIdParameterToJSONTyped,
} from './CashBoxesReadIdParameter';
import type { StoreItemCreateRequestInitialCost } from './StoreItemCreateRequestInitialCost';
import {
    StoreItemCreateRequestInitialCostFromJSON,
    StoreItemCreateRequestInitialCostFromJSONTyped,
    StoreItemCreateRequestInitialCostToJSON,
    StoreItemCreateRequestInitialCostToJSONTyped,
} from './StoreItemCreateRequestInitialCost';

/**
 * 
 * @export
 * @interface StoreItemCreateRequest
 */
export interface StoreItemCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof StoreItemCreateRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof StoreItemCreateRequest
     */
    unitName: string;
    /**
     * 
     * @type {boolean}
     * @memberof StoreItemCreateRequest
     */
    isContainerItem?: boolean;
    /**
     * 
     * @type {Array<CashBoxesReadIdParameter>}
     * @memberof StoreItemCreateRequest
     */
    categoryIds?: Array<CashBoxesReadIdParameter>;
    /**
     * 
     * @type {StoreItemCreateRequestInitialCost}
     * @memberof StoreItemCreateRequest
     */
    initialCost: StoreItemCreateRequestInitialCost;
}

/**
 * Check if a given object implements the StoreItemCreateRequest interface.
 */
export function instanceOfStoreItemCreateRequest(value: object): value is StoreItemCreateRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('unitName' in value) || value['unitName'] === undefined) return false;
    if (!('initialCost' in value) || value['initialCost'] === undefined) return false;
    return true;
}

export function StoreItemCreateRequestFromJSON(json: any): StoreItemCreateRequest {
    return StoreItemCreateRequestFromJSONTyped(json, false);
}

export function StoreItemCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreItemCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'unitName': json['unitName'],
        'isContainerItem': json['isContainerItem'] == null ? undefined : json['isContainerItem'],
        'categoryIds': json['categoryIds'] == null ? undefined : ((json['categoryIds'] as Array<any>).map(CashBoxesReadIdParameterFromJSON)),
        'initialCost': StoreItemCreateRequestInitialCostFromJSON(json['initialCost']),
    };
}

export function StoreItemCreateRequestToJSON(json: any): StoreItemCreateRequest {
    return StoreItemCreateRequestToJSONTyped(json, false);
}

export function StoreItemCreateRequestToJSONTyped(value?: StoreItemCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'unitName': value['unitName'],
        'isContainerItem': value['isContainerItem'],
        'categoryIds': value['categoryIds'] == null ? undefined : ((value['categoryIds'] as Array<any>).map(CashBoxesReadIdParameterToJSON)),
        'initialCost': StoreItemCreateRequestInitialCostToJSON(value['initialCost']),
    };
}

