/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StoreItemCreateRequestInitialCost
 */
export interface StoreItemCreateRequestInitialCost {
}

/**
 * Check if a given object implements the StoreItemCreateRequestInitialCost interface.
 */
export function instanceOfStoreItemCreateRequestInitialCost(value: object): value is StoreItemCreateRequestInitialCost {
    return true;
}

export function StoreItemCreateRequestInitialCostFromJSON(json: any): StoreItemCreateRequestInitialCost {
    return StoreItemCreateRequestInitialCostFromJSONTyped(json, false);
}

export function StoreItemCreateRequestInitialCostFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreItemCreateRequestInitialCost {
    return json;
}

export function StoreItemCreateRequestInitialCostToJSON(json: any): StoreItemCreateRequestInitialCost {
    return StoreItemCreateRequestInitialCostToJSONTyped(json, false);
}

export function StoreItemCreateRequestInitialCostToJSONTyped(value?: StoreItemCreateRequestInitialCost | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

