/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CashBoxesReadIdParameter } from './CashBoxesReadIdParameter';
import {
    CashBoxesReadIdParameterFromJSON,
    CashBoxesReadIdParameterFromJSONTyped,
    CashBoxesReadIdParameterToJSON,
    CashBoxesReadIdParameterToJSONTyped,
} from './CashBoxesReadIdParameter';

/**
 * 
 * @export
 * @interface StoreItemUpdateModel
 */
export interface StoreItemUpdateModel {
    /**
     * 
     * @type {string}
     * @memberof StoreItemUpdateModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof StoreItemUpdateModel
     */
    unitName: string;
    /**
     * 
     * @type {Array<CashBoxesReadIdParameter>}
     * @memberof StoreItemUpdateModel
     */
    categoryIds?: Array<CashBoxesReadIdParameter>;
}

/**
 * Check if a given object implements the StoreItemUpdateModel interface.
 */
export function instanceOfStoreItemUpdateModel(value: object): value is StoreItemUpdateModel {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('unitName' in value) || value['unitName'] === undefined) return false;
    return true;
}

export function StoreItemUpdateModelFromJSON(json: any): StoreItemUpdateModel {
    return StoreItemUpdateModelFromJSONTyped(json, false);
}

export function StoreItemUpdateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreItemUpdateModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'unitName': json['unitName'],
        'categoryIds': json['categoryIds'] == null ? undefined : ((json['categoryIds'] as Array<any>).map(CashBoxesReadIdParameterFromJSON)),
    };
}

export function StoreItemUpdateModelToJSON(json: any): StoreItemUpdateModel {
    return StoreItemUpdateModelToJSONTyped(json, false);
}

export function StoreItemUpdateModelToJSONTyped(value?: StoreItemUpdateModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'unitName': value['unitName'],
        'categoryIds': value['categoryIds'] == null ? undefined : ((value['categoryIds'] as Array<any>).map(CashBoxesReadIdParameterToJSON)),
    };
}

