/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TransactionReason = {
    AddingToStore: 'AddingToStore',
    ChangingStores: 'ChangingStores',
    WriteOff: 'WriteOff',
    Sale: 'Sale',
    StockTaking: 'StockTaking'
} as const;
export type TransactionReason = typeof TransactionReason[keyof typeof TransactionReason];


export function instanceOfTransactionReason(value: any): boolean {
    for (const key in TransactionReason) {
        if (Object.prototype.hasOwnProperty.call(TransactionReason, key)) {
            if (TransactionReason[key as keyof typeof TransactionReason] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TransactionReasonFromJSON(json: any): TransactionReason {
    return TransactionReasonFromJSONTyped(json, false);
}

export function TransactionReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionReason {
    return json as TransactionReason;
}

export function TransactionReasonToJSON(value?: TransactionReason | null): any {
    return value as any;
}

export function TransactionReasonToJSONTyped(value: any, ignoreDiscriminator: boolean): TransactionReason {
    return value as TransactionReason;
}

