/* tslint:disable */
/* eslint-disable */
/**
 * KISv4 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMeta } from './PageMeta';
import {
    PageMetaFromJSON,
    PageMetaFromJSONTyped,
    PageMetaToJSON,
    PageMetaToJSONTyped,
} from './PageMeta';
import type { UserListModel } from './UserListModel';
import {
    UserListModelFromJSON,
    UserListModelFromJSONTyped,
    UserListModelToJSON,
    UserListModelToJSONTyped,
} from './UserListModel';

/**
 * 
 * @export
 * @interface UserReadAllResponse
 */
export interface UserReadAllResponse {
    /**
     * 
     * @type {Array<UserListModel>}
     * @memberof UserReadAllResponse
     */
    data: Array<UserListModel>;
    /**
     * 
     * @type {PageMeta}
     * @memberof UserReadAllResponse
     */
    meta: PageMeta;
}

/**
 * Check if a given object implements the UserReadAllResponse interface.
 */
export function instanceOfUserReadAllResponse(value: object): value is UserReadAllResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function UserReadAllResponseFromJSON(json: any): UserReadAllResponse {
    return UserReadAllResponseFromJSONTyped(json, false);
}

export function UserReadAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserReadAllResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(UserListModelFromJSON)),
        'meta': PageMetaFromJSON(json['meta']),
    };
}

export function UserReadAllResponseToJSON(json: any): UserReadAllResponse {
    return UserReadAllResponseToJSONTyped(json, false);
}

export function UserReadAllResponseToJSONTyped(value?: UserReadAllResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(UserListModelToJSON)),
        'meta': PageMetaToJSON(value['meta']),
    };
}

